"""Static registry of the 10 algorithm demos (pure data, no training).

`fit_score_dimensions` are EDITORIAL ordinals (0-3) — the teaching content that
powers the comparison matrix. They are NOT benchmark performance and must never
be presented as such. `task_family` routes the entry to a trainer in
`trainers.py`.
"""

from __future__ import annotations

from typing import Any

# Supervised models share a core feature block; clustering/PCA use the full set.
SUPERVISED_FEATURES: list[str] = [
    "vix_level",
    "yield_curve_10y2y",
    "credit_spread_hy",
    "btc_mvrv_zscore",
    "crypto_fear_greed",
    "liquidity_index",
    "momentum_63d",
    "term_premium",
]


def _fit(
    interpretability: int,
    handles_nonlinearity: int,
    handles_high_dim: int,
    training_speed: int,
    robust_to_outliers: int,
    needs_scaling: int,
) -> dict[str, int]:
    return {
        "interpretability": interpretability,
        "handles_nonlinearity": handles_nonlinearity,
        "handles_high_dim": handles_high_dim,
        "training_speed": training_speed,
        "robust_to_outliers": robust_to_outliers,
        "needs_scaling": needs_scaling,
    }


ALGORITHM_DEMOS: list[dict[str, Any]] = [
    {
        "id": "linear_regression",
        "name": "Linear Regression",
        "task_type": "regression",
        "task_family": "regression",
        "business_question": "How large will the 30-day forward return be, given today's macro signals?",
        "features": SUPERVISED_FEATURES,
        "target": "forward_return_30d",
        "preprocessing": ["standard_scale"],
        "metrics": ["mae", "rmse", "r2"],
        "charts": ["actual_vs_predicted", "coefficient_bar"],
        "model_card": {
            "best_for": "Continuous numeric estimates where interpretability matters.",
            "not_for": "Nonlinear regime shifts or trap-heavy environments.",
            "preprocessing": "Standardize features; assumes roughly linear relationships.",
            "limitations": "Misses nonlinearity; pulled around by outliers; extrapolates blindly.",
            "decision_this_informs": "A transparent baseline expectation for forward return.",
            "recommended_when": "You need a fast, explainable number and a sanity baseline.",
            "avoid_when": "Relationships break across regimes or extremes dominate.",
        },
        "fit_score_dimensions": _fit(3, 0, 1, 3, 0, 3),
    },
    {
        "id": "logistic_regression",
        "name": "Logistic Regression",
        "task_type": "classification",
        "task_family": "classification",
        "business_question": "What is the probability the next 30 days contain a risk event?",
        "features": SUPERVISED_FEATURES,
        "target": "risk_event_30d",
        "preprocessing": ["standard_scale"],
        "metrics": ["accuracy", "precision", "recall", "f1", "roc_auc"],
        "charts": ["confusion_matrix", "roc_curve", "feature_importance"],
        "model_card": {
            "best_for": "An explainable, calibrated-ish probability baseline for a binary outcome.",
            "not_for": "Strongly nonlinear class boundaries.",
            "preprocessing": "Standardize features; coefficients read as log-odds.",
            "limitations": "Linear decision boundary; accuracy lies under class imbalance.",
            "decision_this_informs": "Whether to escalate risk monitoring this period.",
            "recommended_when": "You want a defensible, transparent classifier first.",
            "avoid_when": "Classes separate only along curved/interaction boundaries.",
        },
        "fit_score_dimensions": _fit(3, 1, 1, 3, 1, 3),
    },
    {
        "id": "decision_tree",
        "name": "Decision Tree",
        "task_type": "classification",
        "task_family": "classification",
        "business_question": "What interpretable rules separate risk from non-risk states?",
        "features": SUPERVISED_FEATURES,
        "target": "risk_event_30d",
        "preprocessing": [],
        "metrics": ["accuracy", "precision", "recall", "f1", "roc_auc"],
        "charts": ["confusion_matrix", "feature_importance"],
        "model_card": {
            "best_for": "Human-readable threshold rules and quick what-drives-it stories.",
            "not_for": "Stable production scoring on noisy data.",
            "preprocessing": "None required; handles raw scales.",
            "limitations": "Overfits; small data perturbations rewrite the rules.",
            "decision_this_informs": "Which thresholds to watch and explain to a committee.",
            "recommended_when": "Interpretable rules matter more than peak accuracy.",
            "avoid_when": "You need stability across re-trains.",
        },
        "fit_score_dimensions": _fit(3, 2, 1, 3, 2, 0),
    },
    {
        "id": "random_forest",
        "name": "Random Forest",
        "task_type": "classification",
        "task_family": "classification",
        "business_question": "Can an ensemble give a more stable risk-event classifier than one tree?",
        "features": SUPERVISED_FEATURES,
        "target": "risk_event_30d",
        "preprocessing": [],
        "metrics": ["accuracy", "precision", "recall", "f1", "roc_auc"],
        "charts": ["confusion_matrix", "feature_importance"],
        "model_card": {
            "best_for": "Strong, stable tabular baseline with feature importances.",
            "not_for": "Cases needing a single transparent rule.",
            "preprocessing": "None required.",
            "limitations": "Less interpretable than one tree; can memorize old regimes.",
            "decision_this_informs": "A robust default risk score for tabular signals.",
            "recommended_when": "You want solid tabular performance with low tuning.",
            "avoid_when": "A single auditable rule is mandatory.",
        },
        "fit_score_dimensions": _fit(1, 3, 2, 2, 3, 0),
    },
    {
        "id": "svm",
        "name": "Support Vector Machine",
        "task_type": "classification",
        "task_family": "classification",
        "business_question": "Can a margin-based boundary separate risk regimes in feature space?",
        "features": SUPERVISED_FEATURES,
        "target": "risk_event_30d",
        "preprocessing": ["standard_scale"],
        "metrics": ["accuracy", "precision", "recall", "f1", "roc_auc"],
        "charts": ["confusion_matrix", "roc_curve"],
        "model_card": {
            "best_for": "Clean margins when classes separate in (kernelized) feature space.",
            "not_for": "Large datasets or hard-interpretability requirements.",
            "preprocessing": "Standardize features; scaling is mandatory.",
            "limitations": "Opaque; slower to train; sensitive to scaling/kernel choice.",
            "decision_this_informs": "Whether a crisp separating boundary exists.",
            "recommended_when": "Moderate data with separable, scaled features.",
            "avoid_when": "You need explanations or scale to large N.",
        },
        "fit_score_dimensions": _fit(1, 3, 3, 1, 2, 3),
    },
    {
        "id": "knn",
        "name": "K-Nearest Neighbors",
        "task_type": "classification",
        "task_family": "classification",
        "business_question": "What happened to the most similar historical observations?",
        "features": SUPERVISED_FEATURES,
        "target": "risk_event_30d",
        "preprocessing": ["standard_scale"],
        "metrics": ["accuracy", "precision", "recall", "f1", "roc_auc"],
        "charts": ["confusion_matrix", "neighbor_table"],
        "model_card": {
            "best_for": "An intuitive analog baseline: classify by nearest neighbors.",
            "not_for": "High-noise, high-dimensional, or scale-uncontrolled data.",
            "preprocessing": "Standardize features; distance is scale-sensitive.",
            "limitations": "Sensitive to scaling and noise; near-duplicates inflate scores.",
            "decision_this_informs": "A simple similarity read before the governed analog engine.",
            "recommended_when": "You want a transparent nearest-analog sanity check.",
            "avoid_when": "Features are noisy/unscaled or duplicates leak across splits.",
        },
        "fit_score_dimensions": _fit(2, 2, 0, 2, 1, 3),
    },
    {
        "id": "naive_bayes",
        "name": "Naive Bayes",
        "task_type": "text_classification",
        "task_family": "text",
        "business_question": "Which theme does a market-narrative snippet belong to?",
        "features": ["narrative_text"],
        "target": "theme",
        "preprocessing": ["count_vectorize"],
        "metrics": ["accuracy", "f1_macro"],
        "charts": ["confusion_matrix", "top_tokens"],
        "model_card": {
            "best_for": "Fast bag-of-words text classification baseline.",
            "not_for": "Text where word order or feature dependence matters.",
            "preprocessing": "Tokenize and count; multinomial likelihood.",
            "limitations": "Naive independence assumption; fragile to adversarial text.",
            "decision_this_informs": "A first-pass theme tag for narrative flow.",
            "recommended_when": "You need a quick, cheap text baseline.",
            "avoid_when": "Narrative is manipulated or context-dependent.",
        },
        "fit_score_dimensions": _fit(2, 1, 3, 3, 1, 0),
    },
    {
        "id": "kmeans",
        "name": "K-Means Clustering",
        "task_type": "clustering",
        "task_family": "clustering",
        "business_question": "What unlabeled market regimes emerge from the signal block?",
        "features": "numeric_block",
        "target": None,
        "preprocessing": ["standard_scale", "pca_project"],
        "metrics": ["silhouette", "inertia"],
        "charts": ["pca_scatter", "cluster_profiles"],
        "model_card": {
            "best_for": "Fast unsupervised segmentation into K regime groups.",
            "not_for": "Non-spherical clusters or unknown K.",
            "preprocessing": "Standardize; project to 2D for display only.",
            "limitations": "Must choose K; assumes roughly spherical clusters.",
            "decision_this_informs": "Candidate regime families for further study.",
            "recommended_when": "You want quick structure discovery.",
            "avoid_when": "Cluster geometry is complex or K is truly unknown.",
        },
        "fit_score_dimensions": _fit(2, 2, 2, 3, 1, 3),
    },
    {
        "id": "hierarchical_clustering",
        "name": "Hierarchical Clustering",
        "task_type": "clustering",
        "task_family": "clustering",
        "business_question": "What nested regime/episode similarity structure exists?",
        "features": "numeric_block",
        "target": None,
        "preprocessing": ["standard_scale"],
        "metrics": ["silhouette"],
        "charts": ["pca_scatter", "cluster_profiles", "dendrogram"],
        "model_card": {
            "best_for": "Exploring nested group structure without choosing K up front.",
            "not_for": "Very large datasets.",
            "preprocessing": "Standardize; Ward linkage on the numeric block.",
            "limitations": "Less scalable; an outlier episode can reshape the tree.",
            "decision_this_informs": "How regimes nest and which episodes group together.",
            "recommended_when": "You want exploratory, hierarchy-aware structure.",
            "avoid_when": "N is large or you need a single flat partition.",
        },
        "fit_score_dimensions": _fit(2, 2, 2, 1, 1, 3),
    },
    {
        "id": "pca",
        "name": "Principal Component Analysis",
        "task_type": "dim_reduction",
        "task_family": "dim_reduction",
        "business_question": "Can many signals be compressed into a few components for visualization?",
        "features": "numeric_block",
        "target": None,
        "preprocessing": ["standard_scale"],
        "metrics": ["explained_variance_ratio", "cumulative_explained_variance"],
        "charts": ["explained_variance_bar", "pca_scatter", "loadings"],
        "model_card": {
            "best_for": "Compression, denoising, and 2D visualization of many features.",
            "not_for": "Direct prediction — PCA is not a model.",
            "preprocessing": "Standardize; components are orthogonal linear combos.",
            "limitations": "Variance is not importance; rare risk signal can hide in low-variance components.",
            "decision_this_informs": "How to visualize and reduce the feature space.",
            "recommended_when": "You need to see/compress high-dimensional state.",
            "avoid_when": "You expect it to predict an outcome on its own.",
        },
        "fit_score_dimensions": _fit(2, 1, 3, 3, 1, 3),
    },
]


ALGORITHM_BY_ID: dict[str, dict[str, Any]] = {d["id"]: d for d in ALGORITHM_DEMOS}


def get_demo(algorithm_id: str) -> dict[str, Any] | None:
    return ALGORITHM_BY_ID.get(algorithm_id)
