import type { HappyCoArtifact } from "./types";

export const HAPPYCO_ARTIFACTS: HappyCoArtifact[] = [
  {
    key: "excel-workbook",
    title: "Excel workbook",
    kind: "Workbook",
    description: "HappyCo_Property_Ops_Model.xlsx with canonical entities, benchmarks, vendor performance, recommendations, ML features, predictions, and metrics.",
    caveat: "Local/private artifact. Upload to gated storage before external download.",
    relativePath: "../artifacts/happyco/excel/HappyCo_Property_Ops_Model.xlsx",
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    fileName: "HappyCo_Property_Ops_Model.xlsx",
  },
  {
    key: "powerpoint-deck",
    title: "PowerPoint deck",
    kind: "Deck",
    description: "HappyCo_90_Day_Data_Strategy.pptx with the strategy, architecture, ML proof, and controls narrative.",
    caveat: "Local/private artifact. Upload to gated storage before external download.",
    relativePath: "../artifacts/happyco/deck/HappyCo_90_Day_Data_Strategy.pptx",
    contentType: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    fileName: "HappyCo_90_Day_Data_Strategy.pptx",
  },
  {
    key: "architecture-svg",
    title: "Architecture SVG",
    kind: "Diagram",
    description: "Source systems -> canonical model -> property graph -> APIs -> ML and artifact outputs.",
    caveat: "Local/private artifact. Upload to gated storage before external download.",
    relativePath: "../artifacts/happyco/architecture/happyco_property_ops_architecture.svg",
    contentType: "image/svg+xml",
    fileName: "happyco_property_ops_architecture.svg",
  },
  {
    key: "databricks-receipt",
    title: "Databricks weather-risk receipt",
    kind: "Receipt JSON",
    description: "Run receipt for the public-weather + synthetic-property-ops Databricks ML proof.",
    caveat: "Receipt-backed claim only. Not HappyCo production data; not a production model; no serving endpoint.",
    relativePath: "../artifacts/happyco/weather-risk/databricks_run_receipt.json",
    contentType: "application/json",
    fileName: "databricks_run_receipt.json",
  },
  {
    key: "api-excerpts",
    title: "API excerpts JSON",
    kind: "API evidence",
    description: "Representative property-ops API payload excerpts showing metadata, caveats, and recommendation evidence.",
    caveat: "Local/private artifact. Upload to gated storage before external download.",
    relativePath: "../artifacts/happyco/qa/api_excerpts.json",
    contentType: "application/json",
    fileName: "api_excerpts.json",
  },
  {
    key: "screenshot-locked",
    title: "Locked package screenshot",
    kind: "Screenshot",
    description: "Proof that HappyCo-specific content starts behind invite-code access.",
    caveat: "Local/private artifact. Upload to gated storage before external download.",
    relativePath: "../artifacts/happyco/screenshots/happyco_locked.png",
    contentType: "image/png",
    fileName: "happyco_locked.png",
  },
  {
    key: "screenshot-unlocked",
    title: "Unlocked package screenshot",
    kind: "Screenshot",
    description: "Proof of the gated package after invite access is granted.",
    caveat: "Local/private artifact. Upload to gated storage before external download.",
    relativePath: "../artifacts/happyco/screenshots/happyco_unlocked.png",
    contentType: "image/png",
    fileName: "happyco_unlocked.png",
  },
  {
    key: "model-card",
    title: "Model card",
    kind: "ML artifact",
    description: "Synthetic-demo model card with model honesty caveats and feature pipeline context.",
    caveat: "Synthetic-demo validation signal only. Not expected HappyCo production performance.",
    relativePath: "../artifacts/happyco/ml/model_card.md",
    contentType: "text/markdown; charset=utf-8",
    fileName: "model_card.md",
  },
  {
    key: "feature-importance",
    title: "Feature importance",
    kind: "ML artifact",
    description: "Feature coefficients/importances for the maintenance escalation risk proof.",
    caveat: "Synthetic-demo validation signal only. Not expected HappyCo production performance.",
    relativePath: "../artifacts/happyco/ml/feature_importance.csv",
    contentType: "text/csv; charset=utf-8",
    fileName: "feature_importance.csv",
  },
  {
    key: "predictions",
    title: "Predictions",
    kind: "ML artifact",
    description: "Batch prediction output for the property operations risk model proof.",
    caveat: "Synthetic-demo validation signal only. Not expected HappyCo production performance.",
    relativePath: "../artifacts/happyco/ml/predictions.csv",
    contentType: "text/csv; charset=utf-8",
    fileName: "predictions.csv",
  },
];
