"""Render a focused, relay-compatible plan per workstream.

Each workstream becomes a standalone plan the relay can run: a title, a
scope section naming owned / read-only / forbidden paths and the dependency
base commit, and an Acceptance Criteria section shaped exactly the way the
relay's intake expects (a heading it recognizes, then concrete bullets under
the six sections). Generation validates the criteria by running them through
`coding_relay.intake.normalize_criteria`, so a child plan the relay would
refuse never reaches a worker.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from orchestration.coding_relay.intake import (
    IntakeError,
    extract_criteria,
    normalize_criteria,
)
from orchestration.relay_coordinator.graph import CoordinatorError, Workstream


@dataclass
class ChildPlan:
    """A generated child plan: its workstream, text, and normalized criteria."""

    workstream_id: str
    title: str
    text: str
    criteria_markdown: str

    def write(self, path: Path) -> Path:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.text, encoding="utf-8")
        return path


def _bullets(items: list[str]) -> list[str]:
    kept = [str(i).strip() for i in items if str(i).strip()]
    return [f"- {b}" for b in kept]


def _paths_block(label: str, paths: list[str]) -> str:
    kept = [str(p).strip() for p in paths if str(p).strip()]
    if not kept:
        return f"- {label}: none"
    return "\n".join([f"- {label}:"] + [f"  - `{p}`" for p in kept])


def render_child_plan(
    ws: Workstream,
    base_commit: str,
    dependency_commits: dict[str, str] | None = None,
) -> ChildPlan:
    """Render a relay-ready plan for one workstream.

    `base_commit` is the fixed SHA the relay worktree branches from.
    `dependency_commits` optionally names the base commit each dependency
    contributed, so the plan states the exact starting state. The generated
    acceptance criteria are validated with the relay's own `normalize_criteria`
    before the plan is returned; a workstream with no judgeable criteria
    raises CoordinatorError here, not at worker-launch time.
    """
    dependency_commits = dependency_commits or {}
    criteria = [str(c).strip() for c in ws.acceptance_criteria if str(c).strip()]
    if not criteria:
        raise CoordinatorError(
            f"workstream {ws.workstream_id} has no acceptance criteria to render"
        )

    dep_lines = []
    for dep in ws.depends_on:
        sha = dependency_commits.get(dep)
        dep_lines.append(f"  - `{dep}`" + (f" at `{sha}`" if sha else ""))
    dep_block = "\n".join(["- Depends on:"] + dep_lines) if dep_lines else "- Depends on: none"

    # Required tests become explicit Evals/tests criteria so the reviewer can
    # judge them; general criteria go under General, which intake keeps as its
    # own group.
    test_bullets = _bullets(ws.required_tests)
    general_bullets = _bullets(criteria)

    forbidden = [str(p).strip() for p in ws.forbidden_paths if str(p).strip()]
    forbidden_criteria = []
    if forbidden:
        forbidden_criteria.append(
            "- No file outside this workstream's owned paths is modified; the "
            "forbidden paths (" + ", ".join(f"`{p}`" for p in forbidden) + ") stay unchanged"
        )

    lines: list[str] = [
        f"# {ws.workstream_id}: {ws.title}",
        "",
        f"Generated by the relay coordinator from workstream `{ws.workstream_id}`.",
        f"Risk: {ws.risk}. Task class routing sets the builder and reviewer models.",
        "",
        "## Scope and boundaries",
        "",
        f"- Base commit: `{base_commit}`",
        dep_block,
        _paths_block("Owned paths (edit only these)", ws.owned_paths),
        _paths_block("Read-only paths (do not modify)", ws.read_only_paths),
        _paths_block("Forbidden paths (never touch)", ws.forbidden_paths),
        "",
        "## Acceptance Criteria",
        "",
        "### General",
        *(general_bullets or ["- Complete the described work"]),
        "",
        "### Screen",
        "Not applicable.",
        "",
        "### API",
        "Not applicable.",
        "",
        "### DB/Data",
        *( ["- Apply the migration in its assigned order"] if ws.migration else ["Not applicable."]),
        "",
        "### AI behavior",
        "Not applicable.",
        "",
        "### Evals/tests",
        *(test_bullets or ["- The inferred test suites for the changed paths run and pass"]),
        "",
        "### Regression guard",
        *(forbidden_criteria or ["- Existing behavior outside the owned paths is unchanged"]),
        "",
    ]
    text = "\n".join(lines) + "\n"

    # Validate through the relay's own intake so a child plan the relay would
    # refuse never leaves the coordinator.
    raw = extract_criteria(text)
    if raw is None:
        raise CoordinatorError(
            f"workstream {ws.workstream_id}: generated plan has no criteria heading "
            "the relay recognizes"
        )
    try:
        normalized = normalize_criteria(raw)
    except IntakeError as exc:
        raise CoordinatorError(
            f"workstream {ws.workstream_id}: generated criteria fail relay intake: {exc}"
        ) from exc

    return ChildPlan(
        workstream_id=ws.workstream_id,
        title=ws.title,
        text=text,
        criteria_markdown=normalized.to_markdown(),
    )
