"""AIA G702/G703 PDF Generator.

Generates AIA Document G702 (Application and Certificate for Payment) and
G703 (Continuation Sheet / Schedule of Values) as PDF using reportlab.
"""
from __future__ import annotations

import io
from decimal import Decimal, ROUND_HALF_UP
from typing import Any
from uuid import UUID

from app.db import get_cursor

try:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ModuleNotFoundError:
    HAS_REPORTLAB = False


def _d(val: Any) -> Decimal:
    if val is None:
        return Decimal("0")
    return Decimal(str(val)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _fmt(val: Decimal) -> str:
    return f"${val:,.2f}"


def generate_g702_g703(
    *,
    draw_request_id: UUID,
    env_id: UUID,
    business_id: UUID,
) -> bytes:
    """Generate combined G702 (summary) + G703 (continuation sheet) PDF."""
    if not HAS_REPORTLAB:
        raise RuntimeError("reportlab is not installed — cannot generate PDF")

    # Fetch data
    with get_cursor() as cur:
        cur.execute(
            """
            SELECT dr.*, p.name AS project_name, p.gc_name, p.address,
                   p.approved_budget, p.original_budget
            FROM cp_draw_request dr
            JOIN pds_projects p ON p.project_id = dr.project_id
            WHERE dr.draw_request_id = %s::uuid AND dr.env_id = %s::uuid AND dr.business_id = %s::uuid
            """,
            (str(draw_request_id), str(env_id), str(business_id)),
        )
        draw = cur.fetchone()
        if not draw:
            raise LookupError(f"Draw request {draw_request_id} not found")

        cur.execute(
            "SELECT * FROM cp_draw_line_item WHERE draw_request_id = %s::uuid ORDER BY cost_code",
            (str(draw_request_id),),
        )
        lines = cur.fetchall()

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER

    # ── Page 1: G702 Summary ──────────────────────────────────────
    _draw_g702_page(c, draw, lines, width, height)

    # ── Page 2+: G703 Continuation Sheet ──────────────────────────
    c.showPage()
    _draw_g703_pages(c, draw, lines, width, height)

    c.save()
    return buf.getvalue()


def _draw_g702_page(
    c: Any, draw: dict, lines: list[dict], width: float, height: float,
) -> None:
    """Render AIA G702 Application and Certificate for Payment."""
    margin = 0.75 * inch
    y = height - margin

    # Header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(margin, y, "AIA Document G702 — Application and Certificate for Payment")
    y -= 24
    c.setFont("Helvetica", 9)
    c.drawString(margin, y, f"Project: {draw.get('project_name', 'N/A')}")
    y -= 14
    c.drawString(margin, y, f"Address: {draw.get('address', 'N/A')}")
    y -= 14
    c.drawString(margin, y, f"Contractor: {draw.get('gc_name', 'N/A')}")
    y -= 14
    c.drawString(margin, y, f"Application No: {draw.get('draw_number', 'N/A')}")
    y -= 14
    period_start = draw.get("billing_period_start", "N/A")
    period_end = draw.get("billing_period_end", "N/A")
    c.drawString(margin, y, f"Period: {period_start} to {period_end}")
    y -= 28

    # G702 summary rows
    original_contract = _d(draw.get("approved_budget") or draw.get("original_budget"))
    total_completed = _d(draw.get("total_previous_draws")) + _d(draw.get("total_current_draw")) + _d(draw.get("total_materials_stored"))
    retainage = _d(draw.get("total_retainage_held"))
    total_earned_less_ret = total_completed - retainage
    previous_certs = _d(draw.get("total_previous_draws"))
    current_due = _d(draw.get("total_amount_due"))
    balance_plus_ret = original_contract - total_earned_less_ret

    rows = [
        ("1. Original Contract Sum", _fmt(original_contract)),
        ("2. Net Change by Change Orders", _fmt(Decimal("0"))),
        ("3. Contract Sum to Date (Line 1 + 2)", _fmt(original_contract)),
        ("4. Total Completed & Stored to Date", _fmt(total_completed)),
        ("5. Retainage", _fmt(retainage)),
        ("6. Total Earned Less Retainage (4 - 5)", _fmt(total_earned_less_ret)),
        ("7. Less Previous Certificates for Payment", _fmt(previous_certs)),
        ("8. Current Payment Due (6 - 7)", _fmt(current_due)),
        ("9. Balance to Finish Plus Retainage (3 - 6)", _fmt(balance_plus_ret)),
    ]

    c.setFont("Helvetica-Bold", 10)
    c.drawString(margin, y, "Summary")
    y -= 18

    for label, value in rows:
        c.setFont("Helvetica", 9)
        c.drawString(margin + 10, y, label)
        c.drawRightString(width - margin, y, value)
        y -= 16

    # Footer
    y -= 20
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(margin, y, "Generated by Winston Construction Draw Management")


def _draw_g703_pages(
    c: Any, draw: dict, lines: list[dict], width: float, height: float,
) -> None:
    """Render AIA G703 Continuation Sheet."""
    margin = 0.75 * inch
    y = height - margin

    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin, y, "AIA Document G703 — Continuation Sheet")
    y -= 16
    c.setFont("Helvetica", 8)
    c.drawString(margin, y, f"Application No: {draw.get('draw_number', 'N/A')}    Project: {draw.get('project_name', 'N/A')}")
    y -= 20

    # Column headers
    cols = [
        ("Item", margin),
        ("Cost Code", margin + 30),
        ("Description", margin + 100),
        ("Sched. Value", margin + 250),
        ("Prev. Draws", margin + 330),
        ("This Period", margin + 400),
        ("Materials", margin + 465),
        ("Total", margin + 520),
        ("% Comp", margin + 580),
        ("Retainage", margin + 620),
        ("Balance", margin + 690),
    ]

    c.setFont("Helvetica-Bold", 7)
    for label, x in cols:
        c.drawString(x, y, label)
    y -= 3
    c.line(margin, y, width - margin, y)
    y -= 12

    # Totals accumulators
    t_sched = t_prev = t_curr = t_mat = t_total = t_ret = t_bal = Decimal("0")

    c.setFont("Helvetica", 7)
    for idx, line in enumerate(lines, 1):
        if y < margin + 40:
            c.showPage()
            y = height - margin
            c.setFont("Helvetica-Bold", 7)
            for label, x in cols:
                c.drawString(x, y, label)
            y -= 3
            c.line(margin, y, width - margin, y)
            y -= 12
            c.setFont("Helvetica", 7)

        sched = _d(line.get("scheduled_value"))
        prev = _d(line.get("previous_draws"))
        curr = _d(line.get("current_draw"))
        mat = _d(line.get("materials_stored"))
        total = _d(line.get("total_completed"))
        pct = _d(line.get("percent_complete"))
        ret = _d(line.get("retainage_amount"))
        bal = _d(line.get("balance_to_finish"))

        t_sched += sched
        t_prev += prev
        t_curr += curr
        t_mat += mat
        t_total += total
        t_ret += ret
        t_bal += bal

        c.drawString(cols[0][1], y, str(idx))
        c.drawString(cols[1][1], y, str(line.get("cost_code", "")))
        desc = str(line.get("description", ""))[:22]
        c.drawString(cols[2][1], y, desc)
        c.drawRightString(cols[3][1] + 70, y, _fmt(sched))
        c.drawRightString(cols[4][1] + 60, y, _fmt(prev))
        c.drawRightString(cols[5][1] + 55, y, _fmt(curr))
        c.drawRightString(cols[6][1] + 45, y, _fmt(mat))
        c.drawRightString(cols[7][1] + 50, y, _fmt(total))
        c.drawRightString(cols[8][1] + 30, y, f"{pct}%")
        c.drawRightString(cols[9][1] + 60, y, _fmt(ret))
        c.drawRightString(cols[10][1] + 60, y, _fmt(bal))
        y -= 12

    # Totals row
    y -= 4
    c.line(margin, y + 8, width - margin, y + 8)
    c.setFont("Helvetica-Bold", 7)
    c.drawString(cols[2][1], y, "TOTALS")
    c.drawRightString(cols[3][1] + 70, y, _fmt(t_sched))
    c.drawRightString(cols[4][1] + 60, y, _fmt(t_prev))
    c.drawRightString(cols[5][1] + 55, y, _fmt(t_curr))
    c.drawRightString(cols[6][1] + 45, y, _fmt(t_mat))
    c.drawRightString(cols[7][1] + 50, y, _fmt(t_total))
    c.drawRightString(cols[9][1] + 60, y, _fmt(t_ret))
    c.drawRightString(cols[10][1] + 60, y, _fmt(t_bal))
