-- 10038_relativity_mes_sandbox_serving.sql
-- SYNTHETIC Relativity MES Sandbox — flat serving marts (rel_*) + lineage manifest.
-- Generated by scripts/relativity_mes_seed (deterministic, master_seed=20260626). DO NOT hand-edit;
-- regenerate with: python -m scripts.relativity_mes_seed.emit
-- Shaped like a Manufacturo MES + generic ERP/PLM facsimile. Not real Relativity data,
-- not a real schema, not a real API. Every row carries synthetic=true.

-- Serving tables are the Postgres/Lakebase read layer the FastAPI routes query. They are
-- BOOTSTRAPPED here from the deterministic gold rows (serving_provenance='seed-bootstrap');
-- the Databricks medallion (telemetry-platform/databricks/relativity_mes) overwrites them
-- with Databricks-computed gold (serving_provenance='databricks-gold') when it runs.

CREATE TABLE IF NOT EXISTS rel_build_overview (
  env_id text NOT NULL DEFAULT 'telemetry-demo',
  business_id uuid NOT NULL DEFAULT '7e1eb000-0000-4000-a000-000000000001',
  vehicle_serial text,
  product_code text,
  build_status text,
  work_order_count numeric,
  genealogy_edge_count numeric,
  installed_component_count numeric,
  open_ncr_count numeric,
  major_ncr_count numeric,
  suspect_lot_count numeric,
  affected_by_suspect_lot boolean,
  planned_cost numeric,
  actual_cost numeric,
  variance_amount numeric,
  variance_pct numeric,
  readiness_state text,
  source_tables text,
  synthetic boolean,
  source_system text,
  source_table text,
  source_pk text,
  ingest_batch_id text,
  as_of timestamptz,
  serving_provenance text
);
ALTER TABLE rel_build_overview ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY rel_build_overview_tenant ON rel_build_overview
    USING (env_id = current_setting('app.env_id', true))
    WITH CHECK (env_id = current_setting('app.env_id', true));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TABLE rel_build_overview IS 'SYNTHETIC gold serving mart (Relativity MES Sandbox), Postgres/Lakebase read layer.';
DELETE FROM rel_build_overview WHERE ingest_batch_id = 'rel-mes-seed-v1';
INSERT INTO rel_build_overview (env_id, business_id, vehicle_serial, product_code, build_status, work_order_count, genealogy_edge_count, installed_component_count, open_ncr_count, major_ncr_count, suspect_lot_count, affected_by_suspect_lot, planned_cost, actual_cost, variance_amount, variance_pct, readiness_state, source_tables, synthetic, source_system, source_table, source_pk, ingest_batch_id, as_of, serving_provenance) VALUES
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'LV-DEMO-R', 'in_assembly', 6, 32, 26, 1, 1, 1, true, 135901.85, 144305.0, 8403.15, 6.18, 'blocked', 'rel_mes_vehicle, rel_mes_work_order, rel_mes_as_built_genealogy, rel_mes_nonconformance, rel_erp_prod_order_cost, rel_erp_cost_variance', true, 'Gold', 'gold.rel_build_overview', 'VEH-DEMO-001', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'LV-DEMO-R', 'in_test', 6, 38, 32, 0, 1, 1, true, 186599.07, 195020.18, 8421.11, 4.51, 'on_track', 'rel_mes_vehicle, rel_mes_work_order, rel_mes_as_built_genealogy, rel_mes_nonconformance, rel_erp_prod_order_cost, rel_erp_cost_variance', true, 'Gold', 'gold.rel_build_overview', 'VEH-DEMO-002', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'LV-DEMO-R', 'in_assembly', 6, 36, 30, 0, 0, 0, false, 188723.44, 194560.25, 5836.81, 3.09, 'on_track', 'rel_mes_vehicle, rel_mes_work_order, rel_mes_as_built_genealogy, rel_mes_nonconformance, rel_erp_prod_order_cost, rel_erp_cost_variance', true, 'Gold', 'gold.rel_build_overview', 'VEH-DEMO-003', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap');

CREATE TABLE IF NOT EXISTS rel_as_built_genealogy (
  env_id text NOT NULL DEFAULT 'telemetry-demo',
  business_id uuid NOT NULL DEFAULT '7e1eb000-0000-4000-a000-000000000001',
  vehicle_serial text,
  parent_node_id text,
  child_node_id text,
  child_type text,
  part_no text,
  part_description text,
  lot_no text,
  unit_serial text,
  reference_designator text,
  install_operation_id text,
  work_order_no text,
  installed_at text,
  installed_by text,
  inspection_result text,
  ncr_id text,
  ncr_status text,
  disposition_type text,
  synthetic boolean,
  source_system text,
  source_table text,
  source_pk text,
  ingest_batch_id text,
  as_of timestamptz,
  serving_provenance text
);
ALTER TABLE rel_as_built_genealogy ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY rel_as_built_genealogy_tenant ON rel_as_built_genealogy
    USING (env_id = current_setting('app.env_id', true))
    WITH CHECK (env_id = current_setting('app.env_id', true));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TABLE rel_as_built_genealogy IS 'SYNTHETIC gold serving mart (Relativity MES Sandbox), Postgres/Lakebase read layer.';
DELETE FROM rel_as_built_genealogy WHERE ingest_batch_id = 'rel-mes-seed-v1';
INSERT INTO rel_as_built_genealogy (env_id, business_id, vehicle_serial, parent_node_id, child_node_id, child_type, part_no, part_description, lot_no, unit_serial, reference_designator, install_operation_id, work_order_no, installed_at, installed_by, inspection_result, ncr_id, ncr_status, disposition_type, synthetic, source_system, source_table, source_pk, ingest_batch_id, as_of, serving_provenance) VALUES
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-VEH', 'SN-001-ENG', 'serial', NULL, NULL, NULL, 'SN-001-ENG', 'RD-ENG', NULL, 'WO-001-ENG', '2026-06-10', 'OP-1177', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00001', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-ENG', 'LOT-2203', 'lot', 'PN-ENG-004', 'Demo Main Engine component 4', 'LOT-2203', NULL, 'RD-ENG-01', NULL, 'WO-001-ENG', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00002', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-ENG', 'LOT-2202', 'lot', 'PN-ENG-001', 'Demo Main Engine component 1', 'LOT-2202', NULL, 'RD-ENG-04', NULL, 'WO-001-ENG', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00003', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-VEH', 'SN-001-TNK', 'serial', NULL, NULL, NULL, 'SN-001-TNK', 'RD-TNK', NULL, 'WO-001-TNK', '2026-06-10', 'OP-1080', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00004', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TNK', 'PN-TNK-003', 'part', 'PN-TNK-003', 'Propellant Tank Assembly component 3', NULL, NULL, 'RD-TNK-03', NULL, 'WO-001-TNK', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00005', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TNK', 'PN-TNK-005', 'part', 'PN-TNK-005', 'Propellant Tank Assembly component 5', NULL, NULL, 'RD-TNK-04', NULL, 'WO-001-TNK', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00006', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TNK', 'LOT-2219', 'lot', 'PN-TNK-002', 'Propellant Tank Assembly component 2', 'LOT-2219', NULL, 'RD-TNK-05', NULL, 'WO-001-TNK', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00007', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TNK', 'LOT-2217', 'lot', 'PN-TNK-001', 'Propellant Tank Assembly component 1', 'LOT-2217', NULL, 'RD-TNK-06', NULL, 'WO-001-TNK', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00008', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TNK', 'PN-TNK-004', 'part', 'PN-TNK-004', 'Propellant Tank Assembly component 4', NULL, NULL, 'RD-TNK-07', NULL, 'WO-001-TNK', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00009', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TNK', 'PN-TNK-005', 'part', 'PN-TNK-005', 'Propellant Tank Assembly component 5', NULL, NULL, 'RD-TNK-08', NULL, 'WO-001-TNK', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00010', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-VEH', 'SN-001-AVB', 'serial', NULL, NULL, NULL, 'SN-001-AVB', 'RD-AVB', NULL, 'WO-001-AVB', '2026-06-10', 'OP-1042', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00011', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-AVB', 'PN-AVB-001', 'part', 'PN-AVB-001', 'Avionics Bay component 1', NULL, NULL, 'RD-AVB-01', NULL, 'WO-001-AVB', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00012', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-03', NULL, 'WO-001-AVB', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00013', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-AVB', 'PN-AVB-004', 'part', 'PN-AVB-004', 'Avionics Bay component 4', NULL, NULL, 'RD-AVB-04', NULL, 'WO-001-AVB', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00014', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-AVB', 'LOT-2200', 'lot', 'PN-AVB-002', 'Avionics Bay component 2', 'LOT-2200', NULL, 'RD-AVB-06', NULL, 'WO-001-AVB', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00015', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-VEH', 'SN-001-STR', 'serial', NULL, NULL, NULL, 'SN-001-STR', 'RD-STR', NULL, 'WO-001-STR', '2026-06-10', 'OP-1080', 'pass', 'NCR-0007', 'closed', 'repair', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00016', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-STR', 'PN-STR-005', 'part', 'PN-STR-005', 'Interstage Structure component 5', NULL, NULL, 'RD-STR-04', NULL, 'WO-001-STR', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00017', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-STR', 'PN-STR-002', 'part', 'PN-STR-002', 'Interstage Structure component 2', NULL, NULL, 'RD-STR-06', NULL, 'WO-001-STR', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00018', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-VEH', 'SN-001-TPS', 'serial', NULL, NULL, NULL, 'SN-001-TPS', 'RD-TPS', NULL, 'WO-001-TPS', '2026-06-10', 'OP-1042', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00019', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TPS', 'PN-TPS-003', 'part', 'PN-TPS-003', 'Thermal Protection Section component 3', NULL, NULL, 'RD-TPS-02', NULL, 'WO-001-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00020', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TPS', 'LOT-2220', 'lot', 'PN-TPS-001', 'Thermal Protection Section component 1', 'LOT-2220', NULL, 'RD-TPS-03', NULL, 'WO-001-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00021', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TPS', 'PN-TPS-003', 'part', 'PN-TPS-003', 'Thermal Protection Section component 3', NULL, NULL, 'RD-TPS-04', NULL, 'WO-001-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00022', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TPS', 'LOT-2225', 'lot', 'PN-TPS-005', 'Thermal Protection Section component 5', 'LOT-2225', NULL, 'RD-TPS-08', NULL, 'WO-001-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00023', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TPS', 'LOT-2222', 'lot', 'PN-TPS-002', 'Thermal Protection Section component 2', 'LOT-2222', NULL, 'RD-TPS-09', NULL, 'WO-001-TPS', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00024', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-VEH', 'SN-001-FED', 'serial', NULL, NULL, NULL, 'SN-001-FED', 'RD-FED', NULL, 'WO-001-FED', '2026-06-10', 'OP-1203', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00025', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-FED', 'LOT-2209', 'lot', 'PN-FED-006', 'Propellant Feed System component 6', 'LOT-2209', NULL, 'RD-FED-03', NULL, 'WO-001-FED', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00026', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-FED', 'PN-FED-007', 'part', 'PN-FED-007', 'Propellant Feed System component 7', NULL, NULL, 'RD-FED-04', NULL, 'WO-001-FED', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00027', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-FED', 'LOT-2208', 'lot', 'PN-FED-005', 'Propellant Feed System component 5', 'LOT-2208', NULL, 'RD-FED-06', NULL, 'WO-001-FED', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00028', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-FED', 'PN-FED-007', 'part', 'PN-FED-007', 'Propellant Feed System component 7', NULL, NULL, 'RD-FED-07', NULL, 'WO-001-FED', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00029', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-FED', 'PN-FED-001', 'part', 'PN-FED-001', 'Propellant Feed System component 1', NULL, NULL, 'RD-FED-08', NULL, 'WO-001-FED', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00030', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-FED', 'LOT-2209', 'lot', 'PN-FED-006', 'Propellant Feed System component 6', 'LOT-2209', NULL, 'RD-FED-09', NULL, 'WO-001-FED', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00031', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-VEH', 'SN-002-ENG', 'serial', NULL, NULL, NULL, 'SN-002-ENG', 'RD-ENG', NULL, 'WO-002-ENG', '2026-06-10', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00032', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-ENG', 'LOT-2202', 'lot', 'PN-ENG-001', 'Demo Main Engine component 1', 'LOT-2202', NULL, 'RD-ENG-01', NULL, 'WO-002-ENG', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00033', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-ENG', 'LOT-2202', 'lot', 'PN-ENG-001', 'Demo Main Engine component 1', 'LOT-2202', NULL, 'RD-ENG-02', NULL, 'WO-002-ENG', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00034', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-ENG', 'PN-ENG-003', 'part', 'PN-ENG-003', 'Demo Main Engine component 3', NULL, NULL, 'RD-ENG-03', NULL, 'WO-002-ENG', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00035', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-ENG', 'LOT-2202', 'lot', 'PN-ENG-001', 'Demo Main Engine component 1', 'LOT-2202', NULL, 'RD-ENG-04', NULL, 'WO-002-ENG', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00036', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-VEH', 'SN-002-TNK', 'serial', NULL, NULL, NULL, 'SN-002-TNK', 'RD-TNK', NULL, 'WO-002-TNK', '2026-06-10', 'OP-1203', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00037', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'PN-TNK-004', 'part', 'PN-TNK-004', 'Propellant Tank Assembly component 4', NULL, NULL, 'RD-TNK-02', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00038', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'PN-TNK-003', 'part', 'PN-TNK-003', 'Propellant Tank Assembly component 3', NULL, NULL, 'RD-TNK-03', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00039', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'PN-TNK-003', 'part', 'PN-TNK-003', 'Propellant Tank Assembly component 3', NULL, NULL, 'RD-TNK-04', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00040', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'LOT-2216', 'lot', 'PN-TNK-001', 'Propellant Tank Assembly component 1', 'LOT-2216', NULL, 'RD-TNK-05', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00041', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'PN-TNK-004', 'part', 'PN-TNK-004', 'Propellant Tank Assembly component 4', NULL, NULL, 'RD-TNK-06', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00042', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'LOT-2218', 'lot', 'PN-TNK-002', 'Propellant Tank Assembly component 2', 'LOT-2218', NULL, 'RD-TNK-07', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00043', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'LOT-2216', 'lot', 'PN-TNK-001', 'Propellant Tank Assembly component 1', 'LOT-2216', NULL, 'RD-TNK-10', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00044', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TNK', 'PN-TNK-005', 'part', 'PN-TNK-005', 'Propellant Tank Assembly component 5', NULL, NULL, 'RD-TNK-11', NULL, 'WO-002-TNK', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00045', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-VEH', 'SN-002-AVB', 'serial', NULL, NULL, NULL, 'SN-002-AVB', 'RD-AVB', NULL, 'WO-002-AVB', '2026-06-10', 'OP-1135', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00046', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-01', NULL, 'WO-002-AVB', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00047', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-02', NULL, 'WO-002-AVB', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00048', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-AVB', 'PN-AVB-004', 'part', 'PN-AVB-004', 'Avionics Bay component 4', NULL, NULL, 'RD-AVB-03', NULL, 'WO-002-AVB', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00049', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-04', NULL, 'WO-002-AVB', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00050', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-AVB', 'PN-AVB-004', 'part', 'PN-AVB-004', 'Avionics Bay component 4', NULL, NULL, 'RD-AVB-06', NULL, 'WO-002-AVB', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00051', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-VEH', 'SN-002-STR', 'serial', NULL, NULL, NULL, 'SN-002-STR', 'RD-STR', NULL, 'WO-002-STR', '2026-06-10', 'OP-1203', NULL, 'NCR-0002', 'closed', 'rework', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00052', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-STR', 'PN-STR-003', 'part', 'PN-STR-003', 'Interstage Structure component 3', NULL, NULL, 'RD-STR-01', NULL, 'WO-002-STR', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00053', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-STR', 'PN-STR-003', 'part', 'PN-STR-003', 'Interstage Structure component 3', NULL, NULL, 'RD-STR-02', NULL, 'WO-002-STR', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00054', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-STR', 'LOT-2210', 'lot', 'PN-STR-001', 'Interstage Structure component 1', 'LOT-2210', NULL, 'RD-STR-03', NULL, 'WO-002-STR', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00055', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-STR', 'PN-STR-005', 'part', 'PN-STR-005', 'Interstage Structure component 5', NULL, NULL, 'RD-STR-04', NULL, 'WO-002-STR', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00056', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-STR', 'LOT-2210', 'lot', 'PN-STR-001', 'Interstage Structure component 1', 'LOT-2210', NULL, 'RD-STR-06', NULL, 'WO-002-STR', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00057', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-STR', 'LOT-2215', 'lot', 'PN-STR-006', 'Interstage Structure component 6', 'LOT-2215', NULL, 'RD-STR-07', NULL, 'WO-002-STR', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00058', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-VEH', 'SN-002-TPS', 'serial', NULL, NULL, NULL, 'SN-002-TPS', 'RD-TPS', NULL, 'WO-002-TPS', '2026-06-10', 'OP-1203', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00059', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TPS', 'PN-TPS-006', 'part', 'PN-TPS-006', 'Thermal Protection Section component 6', NULL, NULL, 'RD-TPS-02', NULL, 'WO-002-TPS', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00060', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TPS', 'LOT-2222', 'lot', 'PN-TPS-002', 'Thermal Protection Section component 2', 'LOT-2222', NULL, 'RD-TPS-03', NULL, 'WO-002-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00061', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TPS', 'PN-TPS-003', 'part', 'PN-TPS-003', 'Thermal Protection Section component 3', NULL, NULL, 'RD-TPS-05', NULL, 'WO-002-TPS', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00062', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TPS', 'PN-TPS-006', 'part', 'PN-TPS-006', 'Thermal Protection Section component 6', NULL, NULL, 'RD-TPS-08', NULL, 'WO-002-TPS', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00063', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-VEH', 'SN-002-FED', 'serial', NULL, NULL, NULL, 'SN-002-FED', 'RD-FED', NULL, 'WO-002-FED', '2026-06-10', 'OP-1042', 'fail', 'NCR-0005', 'closed', 'use-as-is', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00064', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-FED', 'PN-FED-004', 'part', 'PN-FED-004', 'Propellant Feed System component 4', NULL, NULL, 'RD-FED-01', NULL, 'WO-002-FED', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00065', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-FED', 'PN-FED-007', 'part', 'PN-FED-007', 'Propellant Feed System component 7', NULL, NULL, 'RD-FED-04', NULL, 'WO-002-FED', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00066', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-FED', 'LOT-2208', 'lot', 'PN-FED-005', 'Propellant Feed System component 5', 'LOT-2208', NULL, 'RD-FED-05', NULL, 'WO-002-FED', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00067', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-FED', 'PN-FED-004', 'part', 'PN-FED-004', 'Propellant Feed System component 4', NULL, NULL, 'RD-FED-06', NULL, 'WO-002-FED', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00068', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-VEH', 'SN-003-ENG', 'serial', NULL, NULL, NULL, 'SN-003-ENG', 'RD-ENG', NULL, 'WO-003-ENG', '2026-06-10', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00069', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-ENG', 'LOT-2202', 'lot', 'PN-ENG-001', 'Demo Main Engine component 1', 'LOT-2202', NULL, 'RD-ENG-02', NULL, 'WO-003-ENG', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00070', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-ENG', 'PN-ENG-003', 'part', 'PN-ENG-003', 'Demo Main Engine component 3', NULL, NULL, 'RD-ENG-04', NULL, 'WO-003-ENG', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00071', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-ENG', 'PN-ENG-003', 'part', 'PN-ENG-003', 'Demo Main Engine component 3', NULL, NULL, 'RD-ENG-06', NULL, 'WO-003-ENG', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00072', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-ENG', 'LOT-2203', 'lot', 'PN-ENG-004', 'Demo Main Engine component 4', 'LOT-2203', NULL, 'RD-ENG-08', NULL, 'WO-003-ENG', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00073', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-VEH', 'SN-003-TNK', 'serial', NULL, NULL, NULL, 'SN-003-TNK', 'RD-TNK', NULL, 'WO-003-TNK', '2026-06-10', 'OP-1135', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00074', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TNK', 'PN-TNK-004', 'part', 'PN-TNK-004', 'Propellant Tank Assembly component 4', NULL, NULL, 'RD-TNK-02', NULL, 'WO-003-TNK', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00075', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TNK', 'PN-TNK-005', 'part', 'PN-TNK-005', 'Propellant Tank Assembly component 5', NULL, NULL, 'RD-TNK-03', NULL, 'WO-003-TNK', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00076', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TNK', 'PN-TNK-004', 'part', 'PN-TNK-004', 'Propellant Tank Assembly component 4', NULL, NULL, 'RD-TNK-04', NULL, 'WO-003-TNK', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00077', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TNK', 'LOT-2218', 'lot', 'PN-TNK-002', 'Propellant Tank Assembly component 2', 'LOT-2218', NULL, 'RD-TNK-06', NULL, 'WO-003-TNK', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00078', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-VEH', 'SN-003-AVB', 'serial', NULL, NULL, NULL, 'SN-003-AVB', 'RD-AVB', NULL, 'WO-003-AVB', '2026-06-10', 'OP-1042', 'pass', 'NCR-0003', 'closed', 'use-as-is', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00079', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-02', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00080', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'LOT-2201', 'lot', 'PN-AVB-002', 'Avionics Bay component 2', 'LOT-2201', NULL, 'RD-AVB-03', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00081', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-05', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00082', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-001', 'part', 'PN-AVB-001', 'Avionics Bay component 1', NULL, NULL, 'RD-AVB-06', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00083', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-07', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00084', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-004', 'part', 'PN-AVB-004', 'Avionics Bay component 4', NULL, NULL, 'RD-AVB-08', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00085', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-004', 'part', 'PN-AVB-004', 'Avionics Bay component 4', NULL, NULL, 'RD-AVB-09', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00086', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-AVB', 'PN-AVB-003', 'part', 'PN-AVB-003', 'Avionics Bay component 3', NULL, NULL, 'RD-AVB-10', NULL, 'WO-003-AVB', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00087', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-VEH', 'SN-003-STR', 'serial', NULL, NULL, NULL, 'SN-003-STR', 'RD-STR', NULL, 'WO-003-STR', '2026-06-10', 'OP-1177', 'pass', NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00088', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-STR', 'LOT-2210', 'lot', 'PN-STR-001', 'Interstage Structure component 1', 'LOT-2210', NULL, 'RD-STR-03', NULL, 'WO-003-STR', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00089', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-STR', 'PN-STR-003', 'part', 'PN-STR-003', 'Interstage Structure component 3', NULL, NULL, 'RD-STR-04', NULL, 'WO-003-STR', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00090', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-STR', 'PN-STR-003', 'part', 'PN-STR-003', 'Interstage Structure component 3', NULL, NULL, 'RD-STR-07', NULL, 'WO-003-STR', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00091', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-STR', 'PN-STR-003', 'part', 'PN-STR-003', 'Interstage Structure component 3', NULL, NULL, 'RD-STR-09', NULL, 'WO-003-STR', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00092', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-VEH', 'SN-003-TPS', 'serial', NULL, NULL, NULL, 'SN-003-TPS', 'RD-TPS', NULL, 'WO-003-TPS', '2026-06-10', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00093', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TPS', 'LOT-2226', 'lot', 'PN-TPS-005', 'Thermal Protection Section component 5', 'LOT-2226', NULL, 'RD-TPS-01', NULL, 'WO-003-TPS', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00094', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TPS', 'PN-TPS-003', 'part', 'PN-TPS-003', 'Thermal Protection Section component 3', NULL, NULL, 'RD-TPS-02', NULL, 'WO-003-TPS', '2026-06-11', 'OP-1135', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00095', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TPS', 'LOT-2226', 'lot', 'PN-TPS-005', 'Thermal Protection Section component 5', 'LOT-2226', NULL, 'RD-TPS-03', NULL, 'WO-003-TPS', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00096', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TPS', 'PN-TPS-003', 'part', 'PN-TPS-003', 'Thermal Protection Section component 3', NULL, NULL, 'RD-TPS-04', NULL, 'WO-003-TPS', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00097', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TPS', 'LOT-2224', 'lot', 'PN-TPS-004', 'Thermal Protection Section component 4', 'LOT-2224', NULL, 'RD-TPS-06', NULL, 'WO-003-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00098', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-TPS', 'LOT-2223', 'lot', 'PN-TPS-002', 'Thermal Protection Section component 2', 'LOT-2223', NULL, 'RD-TPS-07', NULL, 'WO-003-TPS', '2026-06-11', 'OP-1203', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00099', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-VEH', 'SN-003-FED', 'serial', NULL, NULL, NULL, 'SN-003-FED', 'RD-FED', NULL, 'WO-003-FED', '2026-06-10', 'OP-1203', 'pass', 'NCR-0006', 'closed', 'rework', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00100', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-FED', 'PN-FED-007', 'part', 'PN-FED-007', 'Propellant Feed System component 7', NULL, NULL, 'RD-FED-03', NULL, 'WO-003-FED', '2026-06-11', 'OP-1177', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00101', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-FED', 'LOT-2209', 'lot', 'PN-FED-006', 'Propellant Feed System component 6', 'LOT-2209', NULL, 'RD-FED-05', NULL, 'WO-003-FED', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00102', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-FED', 'LOT-2204', 'lot', 'PN-FED-002', 'Propellant Feed System component 2', 'LOT-2204', NULL, 'RD-FED-06', NULL, 'WO-003-FED', '2026-06-11', 'OP-1080', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00103', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'SN-003-FED', 'PN-FED-004', 'part', 'PN-FED-004', 'Propellant Feed System component 4', NULL, NULL, 'RD-FED-07', NULL, 'WO-003-FED', '2026-06-11', 'OP-1042', NULL, NULL, NULL, NULL, true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00104', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'SN-001-TPS', 'LOT-7788', 'lot', 'PN-TPS-SEAL', 'Thermal protection seal (suspect-lot demo)', 'LOT-7788', NULL, 'RD-TPS-SEAL', NULL, 'WO-001-TPS', '2026-06-11', 'OP-1080', NULL, 'NCR-0001', 'open', 'rework', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00105', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'SN-002-TPS', 'LOT-7788', 'lot', 'PN-TPS-SEAL', 'Thermal protection seal (suspect-lot demo)', 'LOT-7788', NULL, 'RD-TPS-SEAL', NULL, 'WO-002-TPS', '2026-06-11', 'OP-1080', NULL, 'NCR-0001', 'open', 'rework', true, 'Gold', 'gold.rel_as_built_genealogy', 'GE-00106', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap');

CREATE TABLE IF NOT EXISTS rel_ncr_traceability (
  env_id text NOT NULL DEFAULT 'telemetry-demo',
  business_id uuid NOT NULL DEFAULT '7e1eb000-0000-4000-a000-000000000001',
  ncr_id text,
  vehicle_serial text,
  unit_serial_or_lot text,
  part_no text,
  lot_no text,
  work_order_no text,
  operation_id text,
  work_center text,
  defect_code text,
  severity text,
  status text,
  opened_ts text,
  closed_ts text,
  age_days numeric,
  disposition_type text,
  affected_vehicle_count numeric,
  estimated_rework_minutes numeric,
  estimated_rework_cost numeric,
  cluster_label text,
  synthetic boolean,
  source_system text,
  source_table text,
  source_pk text,
  ingest_batch_id text,
  as_of timestamptz,
  serving_provenance text
);
ALTER TABLE rel_ncr_traceability ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY rel_ncr_traceability_tenant ON rel_ncr_traceability
    USING (env_id = current_setting('app.env_id', true))
    WITH CHECK (env_id = current_setting('app.env_id', true));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TABLE rel_ncr_traceability IS 'SYNTHETIC gold serving mart (Relativity MES Sandbox), Postgres/Lakebase read layer.';
DELETE FROM rel_ncr_traceability WHERE ingest_batch_id = 'rel-mes-seed-v1';
INSERT INTO rel_ncr_traceability (env_id, business_id, ncr_id, vehicle_serial, unit_serial_or_lot, part_no, lot_no, work_order_no, operation_id, work_center, defect_code, severity, status, opened_ts, closed_ts, age_days, disposition_type, affected_vehicle_count, estimated_rework_minutes, estimated_rework_cost, cluster_label, synthetic, source_system, source_table, source_pk, ingest_batch_id, as_of, serving_provenance) VALUES
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0001', 'VEH-DEMO-001', 'LOT-7788', 'PN-TPS-SEAL', 'LOT-7788', 'WO-001-TPS', 'OP-TPS-04', 'WC-NDE', 'witness-mark', 'major', 'open', '2026-06-12', NULL, 14, 'rework', 2, 320, 4200.0, 'witness-mark · WC-NDE', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0001', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0002', 'VEH-DEMO-002', 'SN-002-STR', NULL, NULL, 'WO-002-STR', 'OP-STR-03', 'WC-WELD', 'weld-undercut', 'major', 'closed', '2026-06-12', '2026-06-18', 6, 'rework', 1, 210, 2650.0, 'weld-undercut · WC-WELD', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0002', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0003', 'VEH-DEMO-003', 'SN-003-AVB', NULL, NULL, 'WO-003-AVB', 'OP-AVB-02', 'WC-INTEG', 'surface-finish', 'minor', 'closed', '2026-06-12', '2026-06-18', 6, 'use-as-is', 1, 0, 0.0, 'surface-finish · WC-INTEG', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0003', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0004', 'VEH-DEMO-001', 'SN-001-STR', NULL, NULL, 'WO-001-STR', 'OP-STR-06', 'WC-NDE', 'surface-finish', 'minor', 'closed', '2026-06-12', '2026-06-18', 6, 'use-as-is', 1, 0, 0.0, 'surface-finish · WC-NDE', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0004', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0005', 'VEH-DEMO-002', 'SN-002-FED', NULL, NULL, 'WO-002-FED', 'OP-FED-09', 'WC-NDE', 'surface-finish', 'minor', 'closed', '2026-06-12', '2026-06-18', 6, 'use-as-is', 1, 0, 0.0, 'surface-finish · WC-NDE', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0005', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0006', 'VEH-DEMO-003', 'SN-003-FED', NULL, NULL, 'WO-003-FED', 'OP-FED-02', 'WC-NDE', 'surface-finish', 'minor', 'closed', '2026-06-12', '2026-06-18', 6, 'rework', 1, 0, 0.0, 'surface-finish · WC-NDE', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0006', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'NCR-0007', 'VEH-DEMO-001', 'SN-001-STR', NULL, NULL, 'WO-001-STR', 'OP-STR-09', 'WC-NDE', 'torque-out-of-spec', 'minor', 'closed', '2026-06-12', '2026-06-18', 6, 'repair', 1, 0, 0.0, 'torque-out-of-spec · WC-NDE', true, 'Gold', 'gold.rel_ncr_traceability', 'NCR-0007', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap');

CREATE TABLE IF NOT EXISTS rel_build_cost_rollup (
  env_id text NOT NULL DEFAULT 'telemetry-demo',
  business_id uuid NOT NULL DEFAULT '7e1eb000-0000-4000-a000-000000000001',
  vehicle_serial text,
  work_order_no text,
  part_no text,
  material_qty numeric,
  material_actual_cost numeric,
  labor_minutes numeric,
  labor_actual_cost numeric,
  overhead_cost numeric,
  ncr_rework_cost numeric,
  total_actual_cost numeric,
  synthetic boolean,
  source_system text,
  source_table text,
  source_pk text,
  ingest_batch_id text,
  as_of timestamptz,
  serving_provenance text
);
ALTER TABLE rel_build_cost_rollup ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY rel_build_cost_rollup_tenant ON rel_build_cost_rollup
    USING (env_id = current_setting('app.env_id', true))
    WITH CHECK (env_id = current_setting('app.env_id', true));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TABLE rel_build_cost_rollup IS 'SYNTHETIC gold serving mart (Relativity MES Sandbox), Postgres/Lakebase read layer.';
DELETE FROM rel_build_cost_rollup WHERE ingest_batch_id = 'rel-mes-seed-v1';
INSERT INTO rel_build_cost_rollup (env_id, business_id, vehicle_serial, work_order_no, part_no, material_qty, material_actual_cost, labor_minutes, labor_actual_cost, overhead_cost, ncr_rework_cost, total_actual_cost, synthetic, source_system, source_table, source_pk, ingest_batch_id, as_of, serving_provenance) VALUES
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-ENG', 'PN-ENG-004', 5, 13681.77, 737, 1166.92, 210.05, 0.0, 15058.74, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-001-ENG', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-TNK', 'PN-TNK-003', 11, 14403.91, 1577, 2496.92, 449.45, 0.0, 17350.28, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-001-TNK', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-AVB', 'PN-AVB-001', 9, 21202.85, 898, 1421.83, 255.93, 0.0, 22880.61, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-001-AVB', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-STR', 'PN-STR-005', 6, 4859.98, 1032, 1634.0, 294.12, 0.0, 6788.1, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-001-STR', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-TPS', 'PN-TPS-003', 13, 12200.45, 1366, 2162.83, 389.31, 4200.0, 18952.59, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-001-TPS', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-FED', 'PN-FED-006', 13, 56209.55, 1323, 2094.75, 377.06, 0.0, 58681.36, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-001-FED', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-ENG', 'PN-ENG-001', 8, 28013.72, 1484, 2349.67, 422.94, 0.0, 30786.33, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-002-ENG', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-TNK', 'PN-TNK-004', 20, 19799.63, 2019, 3196.75, 575.41, 0.0, 23571.79, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-002-TNK', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-AVB', 'PN-AVB-003', 11, 21869.01, 947, 1499.42, 269.9, 0.0, 23638.33, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-002-AVB', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-STR', 'PN-STR-003', 14, 44014.08, 775, 1227.08, 220.87, 2650.0, 48112.03, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-002-STR', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-TPS', 'PN-TPS-006', 9, 28471.26, 840, 1330.0, 239.4, 0.0, 30040.66, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-002-TPS', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-FED', 'PN-FED-004', 11, 31371.99, 852, 1349.0, 242.82, 0.0, 32963.81, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-002-FED', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-ENG', 'PN-ENG-001', 15, 29220.61, 1522, 2409.83, 433.77, 0.0, 32064.21, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-003-ENG', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-TNK', 'PN-TNK-004', 6, 5651.8, 854, 1352.17, 243.39, 0.0, 7247.36, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-003-TNK', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-AVB', 'PN-AVB-003', 23, 43791.52, 1520, 2406.67, 433.2, 0.0, 46631.39, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-003-AVB', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-STR', 'PN-STR-001', 9, 28936.71, 1763, 2791.42, 502.46, 0.0, 32230.59, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-003-STR', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-TPS', 'PN-TPS-005', 13, 39266.13, 1660, 2628.33, 473.1, 0.0, 42367.56, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-003-TPS', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-FED', 'PN-FED-007', 7, 26152.37, 1042, 1649.83, 296.97, 0.0, 28099.17, true, 'Gold', 'gold.rel_build_cost_rollup', 'WO-003-FED', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap');

CREATE TABLE IF NOT EXISTS rel_mes_erp_reconciliation (
  env_id text NOT NULL DEFAULT 'telemetry-demo',
  business_id uuid NOT NULL DEFAULT '7e1eb000-0000-4000-a000-000000000001',
  vehicle_serial text,
  work_order_no text,
  mfg_order_no text,
  erp_material_id text,
  standard_cost numeric,
  actual_cost numeric,
  variance_amount numeric,
  variance_pct numeric,
  variance_category text,
  source_mes_rows text,
  source_erp_rows text,
  reconciliation_status text,
  synthetic boolean,
  source_system text,
  source_table text,
  source_pk text,
  ingest_batch_id text,
  as_of timestamptz,
  serving_provenance text
);
ALTER TABLE rel_mes_erp_reconciliation ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY rel_mes_erp_reconciliation_tenant ON rel_mes_erp_reconciliation
    USING (env_id = current_setting('app.env_id', true))
    WITH CHECK (env_id = current_setting('app.env_id', true));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TABLE rel_mes_erp_reconciliation IS 'SYNTHETIC gold serving mart (Relativity MES Sandbox), Postgres/Lakebase read layer.';
DELETE FROM rel_mes_erp_reconciliation WHERE ingest_batch_id = 'rel-mes-seed-v1';
INSERT INTO rel_mes_erp_reconciliation (env_id, business_id, vehicle_serial, work_order_no, mfg_order_no, erp_material_id, standard_cost, actual_cost, variance_amount, variance_pct, variance_category, source_mes_rows, source_erp_rows, reconciliation_status, synthetic, source_system, source_table, source_pk, ingest_batch_id, as_of, serving_provenance) VALUES
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-ENG', 'MFG-001-ENG', 'MAT-SUB-ENG', 13611.54, 15058.74, 1447.2, 10.63, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-001-ENG', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-TNK', 'MFG-001-TNK', 'MAT-SUB-TNK', 16496.38, 17350.28, 853.9, 5.18, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-001-TNK', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-AVB', 'MFG-001-AVB', 'MAT-SUB-AVB', 21677.01, 22880.61, 1203.6, 5.55, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-001-AVB', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-STR', 'MFG-001-STR', 'MAT-SUB-STR', 6750.2, 6788.1, 37.9, 0.56, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-001-STR', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-TPS', 'MFG-001-TPS', 'MAT-SUB-TPS', 11124.19, 18952.59, 7828.4, 70.37, 'input_qty', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'exception', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-001-TPS', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-001', 'WO-001-FED', 'MFG-001-FED', 'MAT-SUB-FED', 53344.82, 58681.36, 5336.54, 10.0, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-001-FED', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-ENG', 'MFG-002-ENG', 'MAT-SUB-ENG', 27809.33, 30786.33, 2977.0, 10.71, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-002-ENG', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-TNK', 'MFG-002-TNK', 'MAT-SUB-TNK', 22746.21, 23571.79, 825.58, 3.63, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-002-TNK', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-AVB', 'MFG-002-AVB', 'MAT-SUB-AVB', 21472.0, 23638.33, 2166.33, 10.09, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-002-AVB', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-STR', 'MFG-002-STR', 'MAT-SUB-STR', 45245.94, 48112.03, 2866.09, 6.33, 'resource_usage', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-002-STR', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-TPS', 'MFG-002-TPS', 'MAT-SUB-TPS', 26534.35, 30040.66, 3506.31, 13.21, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-002-TPS', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-002', 'WO-002-FED', 'MFG-002-FED', 'MAT-SUB-FED', 32820.49, 32963.81, 143.32, 0.44, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-002-FED', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-ENG', 'MFG-003-ENG', 'MAT-SUB-ENG', 29919.55, 32064.21, 2144.66, 7.17, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-003-ENG', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-TNK', 'MFG-003-TNK', 'MAT-SUB-TNK', 6707.42, 7247.36, 539.94, 8.05, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-003-TNK', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-AVB', 'MFG-003-AVB', 'MAT-SUB-AVB', 46461.44, 46631.39, 169.95, 0.37, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-003-AVB', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-STR', 'MFG-003-STR', 'MAT-SUB-STR', 29112.44, 32230.59, 3118.15, 10.71, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-003-STR', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-TPS', 'MFG-003-TPS', 'MAT-SUB-TPS', 40246.7, 42367.56, 2120.86, 5.27, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-003-TPS', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'VEH-DEMO-003', 'WO-003-FED', 'MFG-003-FED', 'MAT-SUB-FED', 26370.81, 28099.17, 1728.36, 6.55, 'input_price', 'rel_mes_material_consumption, rel_mes_operation_execution', 'rel_erp_production_order, rel_erp_prod_order_cost, rel_erp_cost_variance', 'reconciled', true, 'Gold', 'gold.rel_mes_erp_reconciliation', 'WO-003-FED', 'rel-mes-seed-v1', '2026-06-26T00:00:00Z', 'seed-bootstrap');

CREATE TABLE IF NOT EXISTS rel_source_lineage_manifest (
  env_id text NOT NULL DEFAULT 'telemetry-demo',
  business_id uuid NOT NULL DEFAULT '7e1eb000-0000-4000-a000-000000000001',
  object_name text,
  layer text,
  source_system text,
  grain text,
  primary_key text,
  row_count numeric,
  dashboard_consumers text,
  join_keys text,
  null_reason text,
  synthetic boolean,
  source_system_layer text,
  as_of timestamptz,
  source_table text,
  source_pk text,
  ingest_batch_id text,
  serving_provenance text
);
ALTER TABLE rel_source_lineage_manifest ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  CREATE POLICY rel_source_lineage_manifest_tenant ON rel_source_lineage_manifest
    USING (env_id = current_setting('app.env_id', true))
    WITH CHECK (env_id = current_setting('app.env_id', true));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
COMMENT ON TABLE rel_source_lineage_manifest IS 'SYNTHETIC source/medallion lineage manifest (Relativity MES Sandbox).';
DELETE FROM rel_source_lineage_manifest WHERE ingest_batch_id = 'rel-mes-seed-v1';
INSERT INTO rel_source_lineage_manifest (env_id, business_id, object_name, layer, source_system, grain, primary_key, row_count, dashboard_consumers, join_keys, null_reason, synthetic, source_system_layer, as_of, source_table, source_pk, ingest_batch_id, serving_provenance) VALUES
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_vehicle', 'source', 'MES', 'vehicle_serial', 'vehicle_serial', 3, '["Build Overview", "Build Genealogy"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_vehicle', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_product', 'source', 'MES', 'product_code', 'product_code', 7, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_product', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_part', 'source', 'MES', 'part_no', 'part_no', 33, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_part', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_lot', 'source', 'MES', 'lot_no', 'lot_no', 29, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_lot', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_unit', 'source', 'MES', 'unit_serial', 'unit_serial', 21, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_unit', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_work_order', 'source', 'MES', 'work_order_no', 'work_order_no', 18, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_work_order', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_operation_execution', 'source', 'MES', 'exec_id', 'exec_id', 153, '["Cost Reconciliation", "Build Genealogy"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_operation_execution', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_as_built_genealogy', 'source', 'MES', 'edge_id', 'edge_id', 106, '["Build Genealogy", "Build Overview"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_as_built_genealogy', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_material_consumption', 'source', 'MES', 'consumption_id', 'consumption_id', 88, '["Cost Reconciliation", "Build Genealogy"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_material_consumption', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_inspection_order', 'source', 'MES', 'inspection_id', 'inspection_id', 27, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_inspection_order', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_nonconformance', 'source', 'MES', 'ncr_id', 'ncr_id', 7, '["NCR Traceability", "Build Genealogy", "Build Overview"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_nonconformance', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_disposition', 'source', 'MES', 'disposition_id', 'disposition_id', 7, '["NCR Traceability", "Build Genealogy"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_disposition', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_erp_material_master', 'source', 'ERP', 'material_id', 'material_id', 33, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_erp_material_master', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_erp_production_order', 'source', 'ERP', 'mfg_order_no', 'mfg_order_no', 18, '["Cost Reconciliation"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_erp_production_order', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_erp_prod_order_cost', 'source', 'ERP', 'cost_id', 'cost_id', 54, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_erp_prod_order_cost', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_erp_cost_variance', 'source', 'ERP', 'variance_id', 'variance_id', 18, '["Cost Reconciliation"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_erp_cost_variance', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_erp_labor_actual', 'source', 'ERP', 'labor_id', 'labor_id', 18, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_erp_labor_actual', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_plm_part', 'source', 'PLM', 'plm_part_no', 'plm_part_no', 33, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_plm_part', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_plm_ebom', 'source', 'PLM', 'ebom_id', 'ebom_id', 1, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_plm_ebom', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_plm_ebom_line', 'source', 'PLM', 'ebom_id', 'ebom_id', 33, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_plm_ebom_line', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_plm_eco', 'source', 'PLM', 'eco_id', 'eco_id', 2, '["Build Genealogy", "Lineage & Source Tables"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_plm_eco', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_plm_effectivity', 'source', 'PLM', 'effectivity_id', 'effectivity_id', 2, '[]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_plm_effectivity', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_xwalk_part_identity', 'source', 'Gold', 'plm_part_no', 'plm_part_no', 33, '["Lineage & Source Tables", "Cost Reconciliation"]', '', NULL, true, 'rel_*', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_xwalk_part_identity', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_build_overview', 'gold/serving', 'Gold', 'computed mart', 'build_status', 3, '[]', '', NULL, true, 'gold.rel_build_overview -> rel_build_overview', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_build_overview', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_as_built_genealogy', 'gold/serving', 'Gold', 'computed mart', 'child_node_id', 106, '[]', '', NULL, true, 'gold.rel_as_built_genealogy -> rel_as_built_genealogy', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_as_built_genealogy', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_ncr_traceability', 'gold/serving', 'Gold', 'computed mart', 'unit_serial_or_lot', 7, '[]', '', NULL, true, 'gold.rel_ncr_traceability -> rel_ncr_traceability', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_ncr_traceability', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_build_cost_rollup', 'gold/serving', 'Gold', 'computed mart', 'part_no', 18, '[]', '', NULL, true, 'gold.rel_build_cost_rollup -> rel_build_cost_rollup', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_build_cost_rollup', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'rel_mes_erp_reconciliation', 'gold/serving', 'Gold', 'computed mart', 'mfg_order_no', 18, '[]', '', NULL, true, 'gold.rel_mes_erp_reconciliation -> rel_mes_erp_reconciliation', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'rel_mes_erp_reconciliation', 'rel-mes-seed-v1', 'seed-bootstrap'),
  ('telemetry-demo', '7e1eb000-0000-4000-a000-000000000001', 'join_key_map', 'doc', 'Gold', 'n/a', 'n/a', 5, '["Lineage & Source Tables"]', '["plm_part_no <-> mes_part_no / product_code <-> erp_material_id (rel_xwalk_part_identity)", "rel_mes_work_order.prod_order_no <-> rel_erp_production_order.mfg_order_no", "rel_mes_lot.lot_no threads rel_mes_material_consumption + rel_mes_as_built_genealogy", "rel_mes_unit.unit_serial threads the genealogy tree", "ncr.unit_serial_or_lot <-> affected vehicle trace"]', NULL, true, 'doc', '2026-06-26T00:00:00Z', 'rel_source_lineage_manifest', 'join_key_map', 'rel-mes-seed-v1', 'seed-bootstrap');

DO $$ DECLARE r record; BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='telemetry_app') THEN
    FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename LIKE 'rel\_%' LOOP
      EXECUTE format('GRANT SELECT ON public.%I TO telemetry_app', r.tablename);
    END LOOP;
  END IF;
END $$;
