-- 527_authoritative_state_uniqueness.sql
-- Enforce one released row per (entity, quarter) on the four authoritative
-- state tables. Adds the 'superseded' promotion_state value, the
-- superseded_at / superseded_by columns to preserve audit lineage when
-- rolling forward, and a partial unique index that hard-fails any future
-- attempt to release a duplicate.
--
-- Pairs with verification/runners/cleanup_released_duplicates.py which
-- handles the existing duplicates. The migration itself is safe to apply
-- before the cleanup because the partial unique index is created only
-- AFTER the cleanup has run (the runner does both: cleanup first, then
-- index creation in the same transaction).
--
-- This migration only widens the CHECK constraint and adds the columns.
-- The unique index is created by the cleanup runner so we don't crash
-- this migration on existing duplicates.

BEGIN;

-- Widen the promotion_state CHECK constraint on the four tables.
DO $$
DECLARE
    tbl text;
BEGIN
    FOR tbl IN
        SELECT unnest(ARRAY[
            're_authoritative_fund_state_qtr',
            're_authoritative_asset_state_qtr',
            're_authoritative_investment_state_qtr',
            're_authoritative_fund_gross_to_net_qtr'
        ])
    LOOP
        EXECUTE format(
            'ALTER TABLE %I DROP CONSTRAINT IF EXISTS %I',
            tbl,
            tbl || '_promotion_state_check'
        );
        -- Find any other CHECK constraint on promotion_state and drop it
        FOR tbl IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = tbl::regclass
              AND contype = 'c'
              AND pg_get_constraintdef(oid) ILIKE '%promotion_state%'
        LOOP
            -- Cannot easily drop dynamically discovered constraints from
            -- inside another DO block — handled per-table below.
            NULL;
        END LOOP;
    END LOOP;
END$$;

-- Drop the existing CHECK constraints by their actual names. These were
-- generated by Postgres so we need to find them by introspection.
DO $$
DECLARE
    cn text;
    tbl text;
BEGIN
    FOR tbl IN VALUES
        ('re_authoritative_fund_state_qtr'),
        ('re_authoritative_asset_state_qtr'),
        ('re_authoritative_investment_state_qtr'),
        ('re_authoritative_fund_gross_to_net_qtr')
    LOOP
        FOR cn IN
            SELECT conname FROM pg_constraint
            WHERE conrelid = tbl::regclass
              AND contype = 'c'
              AND pg_get_constraintdef(oid) ILIKE '%promotion_state%'
        LOOP
            EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', tbl, cn);
        END LOOP;
    END LOOP;
END$$;

-- Re-add CHECK constraints that include 'superseded'
ALTER TABLE re_authoritative_fund_state_qtr
    ADD CONSTRAINT re_authoritative_fund_state_qtr_promotion_state_check
    CHECK (promotion_state IN ('draft_audit', 'verified', 'released', 'superseded'));

ALTER TABLE re_authoritative_asset_state_qtr
    ADD CONSTRAINT re_authoritative_asset_state_qtr_promotion_state_check
    CHECK (promotion_state IN ('draft_audit', 'verified', 'released', 'superseded'));

ALTER TABLE re_authoritative_investment_state_qtr
    ADD CONSTRAINT re_authoritative_investment_state_qtr_promotion_state_check
    CHECK (promotion_state IN ('draft_audit', 'verified', 'released', 'superseded'));

ALTER TABLE re_authoritative_fund_gross_to_net_qtr
    ADD CONSTRAINT re_authoritative_fund_gross_to_net_qtr_promotion_state_check
    CHECK (promotion_state IN ('draft_audit', 'verified', 'released', 'superseded'));

-- Add superseded_at / superseded_by columns. NULL when promotion_state != 'superseded'.
-- superseded_by points to the canonical released row that replaced this one,
-- so the audit chain is traversable: superseded.id → canonical.id.
ALTER TABLE re_authoritative_fund_state_qtr
    ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS superseded_by UUID REFERENCES re_authoritative_fund_state_qtr(id);

ALTER TABLE re_authoritative_asset_state_qtr
    ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS superseded_by UUID REFERENCES re_authoritative_asset_state_qtr(id);

ALTER TABLE re_authoritative_investment_state_qtr
    ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS superseded_by UUID REFERENCES re_authoritative_investment_state_qtr(id);

ALTER TABLE re_authoritative_fund_gross_to_net_qtr
    ADD COLUMN IF NOT EXISTS superseded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS superseded_by UUID REFERENCES re_authoritative_fund_gross_to_net_qtr(id);

-- Sanity check: superseded rows must have superseded_at, non-superseded must not.
ALTER TABLE re_authoritative_fund_state_qtr
    ADD CONSTRAINT re_authoritative_fund_state_qtr_superseded_consistency
    CHECK (
        (promotion_state = 'superseded' AND superseded_at IS NOT NULL)
        OR
        (promotion_state != 'superseded' AND superseded_at IS NULL)
    );

ALTER TABLE re_authoritative_asset_state_qtr
    ADD CONSTRAINT re_authoritative_asset_state_qtr_superseded_consistency
    CHECK (
        (promotion_state = 'superseded' AND superseded_at IS NOT NULL)
        OR
        (promotion_state != 'superseded' AND superseded_at IS NULL)
    );

ALTER TABLE re_authoritative_investment_state_qtr
    ADD CONSTRAINT re_authoritative_investment_state_qtr_superseded_consistency
    CHECK (
        (promotion_state = 'superseded' AND superseded_at IS NOT NULL)
        OR
        (promotion_state != 'superseded' AND superseded_at IS NULL)
    );

ALTER TABLE re_authoritative_fund_gross_to_net_qtr
    ADD CONSTRAINT re_authoritative_fund_gross_to_net_qtr_superseded_consistency
    CHECK (
        (promotion_state = 'superseded' AND superseded_at IS NOT NULL)
        OR
        (promotion_state != 'superseded' AND superseded_at IS NULL)
    );

COMMENT ON COLUMN re_authoritative_fund_state_qtr.superseded_at IS
    'When this released row was superseded by a newer release. NULL unless promotion_state = ''superseded''.';
COMMENT ON COLUMN re_authoritative_fund_state_qtr.superseded_by IS
    'FK to the row that replaced this one. NULL if no replacement exists yet.';

COMMIT;
