apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-feature-store-ingest
  namespace: winston-streaming
  annotations:
    iam.gke.io/gcp-service-account: hr-feature-store-ingest@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-feature-store-materializer
  namespace: winston-streaming
  annotations:
    iam.gke.io/gcp-service-account: hr-feature-store-materializer@PROJECT_ID.iam.gserviceaccount.com
