# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stargate_telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stargate_telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18stargate_telemetry.proto\x12\x0bstargate.v1\"\xce\x01\n\x11StargateTelemetry\x12\x12\n\nprinter_id\x18\x01 \x01(\t\x12\r\n\x05ts_us\x18\x02 \x01(\x03\x12\r\n\x05layer\x18\x03 \x01(\r\x12\x14\n\x0cprint_job_id\x18\x04 \x01(\t\x12\t\n\x01x\x18\x05 \x01(\x01\x12\t\n\x01y\x18\x06 \x01(\x01\x12\t\n\x01z\x18\x07 \x01(\x01\x12\x18\n\x10melt_pool_temp_c\x18\x08 \x01(\x01\x12\x1d\n\x15\x64\x65position_rate_kg_hr\x18\t \x01(\x01\x12\x17\n\x0f\x61rm_vibration_g\x18\n \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stargate_telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARGATETELEMETRY']._serialized_start=42
  _globals['_STARGATETELEMETRY']._serialized_end=248
# @@protoc_insertion_point(module_scope)
