apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-feature-store-ingest
  namespace: winston-streaming
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hr-feature-store-materializer
  namespace: winston-streaming
