"""
seed_workspace.py — Upload and run the supply chain demo seeding script.

Builds a self-contained Databricks notebook that creates 19 Delta tables
(7 bronze, 7 silver, 5 semantic) and submits it via the Jobs API.

Usage:
    cp .env.example .env
    # fill in DATABRICKS_HOST, DATABRICKS_TOKEN, DATABRICKS_CLUSTER_ID
    python seed_workspace.py

Requirements: requests, python-dotenv
"""

import base64
import os
import sys
import time

import requests
from dotenv import load_dotenv

load_dotenv()

HOST = os.environ.get("DATABRICKS_HOST", "").rstrip("/")
TOKEN = os.environ.get("DATABRICKS_TOKEN", "")
CLUSTER_ID = os.environ.get("DATABRICKS_CLUSTER_ID", "")
ALLOW_NEW_CLUSTER = os.environ.get("DATABRICKS_ALLOW_NEW_CLUSTER", "false").lower() == "true"
NOTEBOOK_PATH_CFG = os.environ.get("DATABRICKS_NOTEBOOK_PATH", "/Users/<your-email@domain.com>/supply_chain_demo")
CATALOG = os.environ.get("DATABRICKS_CATALOG", "supply_chain_demo")
BRONZE = os.environ.get("DATABRICKS_BRONZE_SCHEMA", "bronze")
SILVER = os.environ.get("DATABRICKS_SILVER_SCHEMA", "silver")
SEMANTIC = os.environ.get("DATABRICKS_GOLD_SCHEMA", "semantic")

POLL_INTERVAL = 10
TIMEOUT_SECONDS = 900


def _headers():
    return {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}


def _get(path):
    r = requests.get(f"{HOST}{path}", headers=_headers(), timeout=30)
    r.raise_for_status()
    return r.json()


def _post(path, payload):
    r = requests.post(f"{HOST}{path}", json=payload, headers=_headers(), timeout=30)
    r.raise_for_status()
    return r.json()


def _post_raw(path, payload):
    r = requests.post(f"{HOST}{path}", json=payload, headers=_headers(), timeout=30)
    return r


def preflight():
    if not HOST or not TOKEN:
        print("ERROR: DATABRICKS_HOST and DATABRICKS_TOKEN are required.")
        sys.exit(1)
    if not CLUSTER_ID and not ALLOW_NEW_CLUSTER:
        print(
            "ERROR: DATABRICKS_CLUSTER_ID is required.\n"
            "Set it to a running all-purpose cluster ID, or set\n"
            "DATABRICKS_ALLOW_NEW_CLUSTER=true to provision an ephemeral cluster."
        )
        sys.exit(1)


def resolve_notebook_path():
    path = NOTEBOOK_PATH_CFG
    if "<your-email@domain.com>" in path:
        try:
            me = _get("/api/2.0/preview/scim/v2/Me")
            email = me.get("userName", "")
            if email:
                path = path.replace("<your-email@domain.com>", email)
                print(f"  auto-detected user email: {email}")
        except Exception as e:
            print(f"  warning: could not auto-detect email ({e}); using path as-is")
    return path.rstrip("/")


def build_seed_script():
    return f'''# Databricks notebook source
# Supply Chain Demo — Seed All Tables
# Generated by seed_workspace.py. Do not edit directly.

import random
from datetime import date, timedelta
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window
from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType, DoubleType, BooleanType, DateType
)

random.seed(42)
spark = SparkSession.builder.getOrCreate()

CATALOG = "{CATALOG}"
BRONZE = "{BRONZE}"
SILVER = "{SILVER}"
SEMANTIC = "{SEMANTIC}"

USE_UNITY = True
try:
    spark.sql(f"CREATE CATALOG IF NOT EXISTS {{CATALOG}}")
    spark.sql(f"USE CATALOG {{CATALOG}}")
    for schema in (BRONZE, SILVER, SEMANTIC):
        spark.sql(f"CREATE SCHEMA IF NOT EXISTS {{CATALOG}}.{{schema}}")
    print(f"Unity Catalog ready: {{CATALOG}}.{{{{BRONZE,SILVER,SEMANTIC}}}}")
except Exception as _e:
    USE_UNITY = False
    print(f"Unity Catalog unavailable ({{type(_e).__name__}}). Using hive_metastore fallback.")
    for schema in (BRONZE, SILVER, SEMANTIC):
        spark.sql(f"CREATE DATABASE IF NOT EXISTS {{CATALOG}}_{{schema}}")


def table_ref(schema, name):
    if USE_UNITY:
        return f"{{CATALOG}}.{{schema}}.{{name}}"
    return f"{{CATALOG}}_{{schema}}.{{name}}"


TODAY = date.today()
_BASE_DATE = date(TODAY.year - 1, TODAY.month, TODAY.day)

_SUPPLIER_NAMES = [
    "Apex Logistics", "Blue Ridge Manufacturing", "Canton Exports Ltd",
    "Delta Components", "Eastfield Precision", "Fujiyama Parts",
    "Greenleaf Assembly", "Horizon Metals", "Inland Pacific Trading",
    "JKL Electronics", "Keystone Raw Materials", "Lima Fasteners",
    "Meridian Plastics", "Northbrook Steel", "Omega Circuit Works",
    "Pinnacle Textiles", "Quantum Sensors", "Redwood Forest Products",
    "Summit Castings", "Triton Marine Parts",
]
_CATEGORIES = ["Electronics", "Metals", "Plastics", "Textiles", "Chemicals", "Packaging"]
_REGIONS = ["Northeast", "Southeast", "Midwest", "Southwest", "West", "International"]

# ---------------------------------------------------------------------------
# Bronze layer
# ---------------------------------------------------------------------------

def gen_supplier_master():
    rows = [
        (f"SUP{i:03d}", _SUPPLIER_NAMES[i], _CATEGORIES[i % len(_CATEGORIES)],
         _REGIONS[i % len(_REGIONS)], round(random.uniform(0.6, 1.0), 3))
        for i in range(20)
    ]
    schema = StructType([
        StructField("supplier_id", StringType(), False),
        StructField("supplier_name", StringType(), True),
        StructField("category", StringType(), True),
        StructField("region", StringType(), True),
        StructField("reliability_score", DoubleType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_supplier_master"))
    return df.count()

def gen_item_master():
    rows = [
        (f"SKU{i:04d}", f"Item {{i:04d}} {{_CATEGORIES[i % len(_CATEGORIES)]}}",
         _CATEGORIES[i % len(_CATEGORIES)], round(random.uniform(5.0, 500.0), 2),
         random.choice(["EA", "CASE", "BOX", "PALLET"]))
        for i in range(200)
    ]
    schema = StructType([
        StructField("sku_id", StringType(), False),
        StructField("sku_description", StringType(), True),
        StructField("category", StringType(), True),
        StructField("unit_cost", DoubleType(), True),
        StructField("unit_of_measure", StringType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_item_master"))
    return df.count()

def gen_location_master():
    rows = [
        (f"WH{{i:02d}}", f"Warehouse {{i:02d}}", _REGIONS[i % len(_REGIONS)],
         round(random.uniform(10000, 500000), 0))
        for i in range(10)
    ]
    schema = StructType([
        StructField("warehouse_id", StringType(), False),
        StructField("warehouse_name", StringType(), True),
        StructField("region", StringType(), True),
        StructField("capacity_sqft", DoubleType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_location_master"))
    return df.count()

def gen_purchase_orders():
    rows = []
    for i in range(10000):
        po_date = _BASE_DATE + timedelta(days=random.randint(0, 365))
        po_date_str = None if random.random() < 0.02 else str(po_date)
        qty = random.randint(-5, 500) if random.random() < 0.01 else random.randint(1, 500)
        po_number = f"PO{{i:06d}}"
        if random.random() < 0.005:
            po_number = f"PO{{random.randint(0, i):06d}}"
        rows.append((
            po_number,
            f"SUP{{random.randint(0, 19):03d}}",
            f"SKU{{random.randint(0, 199):04d}}",
            po_date_str,
            qty,
            random.choice(["OPEN", "CONFIRMED", "SHIPPED", "RECEIVED", "CANCELLED"]),
        ))
    schema = StructType([
        StructField("po_number", StringType(), False),
        StructField("supplier_id", StringType(), True),
        StructField("sku_id", StringType(), True),
        StructField("po_date", StringType(), True),
        StructField("ordered_qty", IntegerType(), True),
        StructField("status", StringType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_purchase_orders"))
    return df.count()

def gen_shipments():
    rows = []
    for i in range(20000):
        ship_date = _BASE_DATE + timedelta(days=random.randint(0, 365))
        delay_days = random.choices([0, 0, 0, 1, 2, 5, 10], weights=[40, 20, 15, 10, 7, 5, 3])[0]
        delivery_date = ship_date + timedelta(days=delay_days)
        ship_date_str = None if random.random() < 0.03 else str(ship_date)
        qty = random.randint(1, 300)
        rows.append((
            f"SHP{{i:07d}}",
            f"PO{{random.randint(0, 9999):06d}}",
            f"SUP{{random.randint(0, 19):03d}}",
            f"SKU{{random.randint(0, 199):04d}}",
            f"WH{{random.randint(0, 9):02d}}",
            ship_date_str,
            str(delivery_date),
            qty,
            round(random.uniform(50, 2000), 2),
        ))
    schema = StructType([
        StructField("shipment_id", StringType(), False),
        StructField("po_number", StringType(), True),
        StructField("supplier_id", StringType(), True),
        StructField("sku_id", StringType(), True),
        StructField("warehouse_id", StringType(), True),
        StructField("ship_date", StringType(), True),
        StructField("delivery_date", StringType(), True),
        StructField("shipped_qty", IntegerType(), True),
        StructField("freight_cost", DoubleType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_shipments"))
    return df.count()

def gen_inventory_snapshots():
    rows = []
    skus_per_wh = [f"SKU{{random.randint(0, 199):04d}}" for _ in range(20)]
    for day_offset in range(90):
        snap_date = str(_BASE_DATE + timedelta(days=day_offset))
        for wh in range(10):
            for sku in skus_per_wh:
                on_hand = random.randint(-10, 2000) if random.random() < 0.01 else random.randint(0, 2000)
                rows.append((
                    snap_date,
                    f"WH{{wh:02d}}",
                    sku,
                    on_hand,
                    round(random.uniform(10, 200), 1),
                ))
    schema = StructType([
        StructField("snapshot_date", StringType(), False),
        StructField("warehouse_id", StringType(), False),
        StructField("sku_id", StringType(), False),
        StructField("on_hand_qty", IntegerType(), True),
        StructField("avg_daily_demand", DoubleType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_inventory_snapshots"))
    return df.count()

def gen_production_events():
    rows = []
    for i in range(5000):
        event_date = str(_BASE_DATE + timedelta(days=random.randint(0, 365)))
        planned = random.randint(100, 1000)
        actual = int(planned * random.uniform(0.7, 1.15))
        rows.append((
            f"PROD{{i:06d}}",
            f"WH{{random.randint(0, 9):02d}}",
            f"SKU{{random.randint(0, 199):04d}}",
            event_date,
            planned,
            actual,
            round(random.uniform(0.5, 8.0), 2),
        ))
    schema = StructType([
        StructField("event_id", StringType(), False),
        StructField("location_id", StringType(), True),
        StructField("sku_id", StringType(), True),
        StructField("event_date", StringType(), True),
        StructField("planned_output", IntegerType(), True),
        StructField("actual_output", IntegerType(), True),
        StructField("downtime_hours", DoubleType(), True),
    ])
    df = spark.createDataFrame(rows, schema)
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(BRONZE, "raw_production_events"))
    return df.count()

# ---------------------------------------------------------------------------
# Silver layer
# ---------------------------------------------------------------------------

def build_dim_supplier():
    df = spark.read.table(table_ref(BRONZE, "raw_supplier_master"))
    w = Window.partitionBy("supplier_id").orderBy(F.monotonically_increasing_id())
    df = df.withColumn("_rn", F.row_number().over(w)).filter(F.col("_rn") == 1).drop("_rn")
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "dim_supplier"))
    return df.count()

def build_dim_item():
    df = spark.read.table(table_ref(BRONZE, "raw_item_master"))
    w = Window.partitionBy("sku_id").orderBy(F.monotonically_increasing_id())
    df = df.withColumn("_rn", F.row_number().over(w)).filter(F.col("_rn") == 1).drop("_rn")
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "dim_item"))
    return df.count()

def build_dim_location():
    df = spark.read.table(table_ref(BRONZE, "raw_location_master"))
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "dim_location"))
    return df.count()

def build_fact_inventory_position():
    df = spark.read.table(table_ref(BRONZE, "raw_inventory_snapshots"))
    df = df.withColumn("snapshot_date", F.to_date("snapshot_date"))
    df = df.filter(F.col("on_hand_qty") >= 0)
    df = df.withColumn("days_of_supply",
        F.when(F.col("avg_daily_demand") > 0,
               F.col("on_hand_qty") / F.col("avg_daily_demand")).otherwise(None)
    )
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "fact_inventory_position"))
    return df.count()

def build_fact_order_cycle():
    df = spark.read.table(table_ref(BRONZE, "raw_purchase_orders"))
    df = df.filter(F.col("po_date").isNotNull())
    df = df.filter(F.col("ordered_qty") > 0)
    df = df.withColumn("po_date", F.to_date("po_date"))
    w = Window.partitionBy("po_number").orderBy(F.col("po_date").desc())
    df = df.withColumn("_rn", F.row_number().over(w)).filter(F.col("_rn") == 1).drop("_rn")
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "fact_order_cycle"))
    return df.count()

def build_fact_shipment_event():
    df = spark.read.table(table_ref(BRONZE, "raw_shipments"))
    df = df.filter(F.col("ship_date").isNotNull())
    df = df.withColumn("ship_date", F.to_date("ship_date"))
    df = df.withColumn("delivery_date", F.to_date("delivery_date"))
    df = df.join(
        spark.read.table(table_ref(BRONZE, "raw_purchase_orders"))
            .filter(F.col("po_date").isNotNull())
            .filter(F.col("ordered_qty") > 0)
            .select("po_number", F.to_date("po_date").alias("po_date"), "ordered_qty"),
        on="po_number", how="left"
    )
    df = df.withColumn(
        "on_time", F.col("delivery_date") <= F.col("po_date") + F.expr("INTERVAL 14 DAYS")
    )
    df = df.withColumn(
        "in_full", F.col("shipped_qty") >= (F.col("ordered_qty") * F.lit(0.95))
    )
    df = df.withColumn("otif_flag", F.col("on_time") & F.col("in_full"))
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "fact_shipment_event"))
    return df.count()

def build_fact_production_output():
    df = spark.read.table(table_ref(BRONZE, "raw_production_events"))
    df = df.filter(F.col("actual_output") >= 0)
    df = df.withColumn("event_date", F.to_date("event_date"))
    df = df.withColumn(
        "efficiency_pct",
        F.when(F.col("planned_output") > 0,
               (F.col("actual_output") / F.col("planned_output")) * 100).otherwise(None)
    )
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SILVER, "fact_production_output"))
    return df.count()

# ---------------------------------------------------------------------------
# Semantic layer (gold aggregations)
# ---------------------------------------------------------------------------

def build_supplier_otif_scorecard():
    df = spark.read.table(table_ref(SILVER, "fact_shipment_event"))
    df = df.filter(F.col("ship_date").isNotNull())
    df = df.withColumn("period_month", F.date_trunc("month", "ship_date"))
    df = df.join(
        spark.read.table(table_ref(SILVER, "dim_supplier")).select("supplier_id", "supplier_name"),
        on="supplier_id", how="left"
    )
    agg = df.groupBy("supplier_id", "supplier_name", "period_month").agg(
        F.count("*").alias("total_shipments"),
        F.sum(F.col("otif_flag").cast("int")).alias("otif_shipments"),
    )
    agg = agg.withColumn(
        "otif_pct",
        F.round((F.col("otif_shipments") / F.col("total_shipments")) * 100, 2)
    )
    agg.write.format("delta").mode("overwrite").saveAsTable(table_ref(SEMANTIC, "supplier_otif_scorecard"))
    return agg.count()

def build_inventory_risk_daily():
    df = spark.read.table(table_ref(SILVER, "fact_inventory_position"))
    df = df.join(
        spark.read.table(table_ref(SILVER, "dim_item")).select("sku_id", "sku_description", "category"),
        on="sku_id", how="left"
    )
    df = df.withColumn(
        "risk_tier",
        F.when(F.col("days_of_supply") < 7, "CRITICAL")
         .when(F.col("days_of_supply") < 14, "AT_RISK")
         .when(F.col("days_of_supply") < 30, "WATCH")
         .otherwise("HEALTHY")
    )
    df.write.format("delta").mode("overwrite").saveAsTable(table_ref(SEMANTIC, "inventory_risk_daily"))
    return df.count()

def build_demand_supply_gap():
    po = spark.read.table(table_ref(SILVER, "fact_order_cycle"))
    po = po.withColumn("period_month", F.date_trunc("month", "po_date"))
    demand = po.groupBy("sku_id", "period_month").agg(
        F.sum("ordered_qty").alias("demand_qty")
    )
    ship = spark.read.table(table_ref(SILVER, "fact_shipment_event"))
    ship = ship.withColumn("period_month", F.date_trunc("month", "ship_date"))
    supply = ship.groupBy("sku_id", "period_month").agg(
        F.sum("shipped_qty").alias("supply_qty")
    )
    gap = demand.join(supply, on=["sku_id", "period_month"], how="outer")
    gap = gap.withColumn(
        "gap_qty", F.coalesce(F.col("supply_qty"), F.lit(0)) - F.coalesce(F.col("demand_qty"), F.lit(0))
    )
    gap = gap.withColumn(
        "gap_pct",
        F.when(F.col("demand_qty") > 0,
               F.round((F.col("gap_qty") / F.col("demand_qty")) * 100, 2)).otherwise(None)
    )
    gap.write.format("delta").mode("overwrite").saveAsTable(table_ref(SEMANTIC, "demand_supply_gap"))
    return gap.count()

def build_logistics_cost_to_serve():
    df = spark.read.table(table_ref(SILVER, "fact_shipment_event"))
    df = df.filter(F.col("ship_date").isNotNull())
    df = df.withColumn("period_month", F.date_trunc("month", "ship_date"))
    df = df.join(
        spark.read.table(table_ref(SILVER, "dim_supplier")).select("supplier_id", "supplier_name", "region"),
        on="supplier_id", how="left"
    )
    agg = df.groupBy("supplier_id", "supplier_name", "region", "warehouse_id", "period_month").agg(
        F.count("*").alias("shipment_count"),
        F.sum("freight_cost").alias("total_freight_cost"),
        F.sum("shipped_qty").alias("total_units"),
    )
    agg = agg.withColumn(
        "cost_per_unit",
        F.when(F.col("total_units") > 0,
               F.round(F.col("total_freight_cost") / F.col("total_units"), 4)).otherwise(None)
    )
    agg.write.format("delta").mode("overwrite").saveAsTable(table_ref(SEMANTIC, "logistics_cost_to_serve"))
    return agg.count()

def build_production_throughput_summary():
    df = spark.read.table(table_ref(SILVER, "fact_production_output"))
    df = df.withColumn("period_month", F.date_trunc("month", "event_date"))
    df = df.join(
        spark.read.table(table_ref(SILVER, "dim_location")).select("warehouse_id", "warehouse_name", "region"),
        df.location_id == F.col("warehouse_id"), how="left"
    )
    agg = df.groupBy("location_id", "warehouse_name", "region", "period_month").agg(
        F.sum("planned_output").alias("planned_units"),
        F.sum("actual_output").alias("actual_units"),
        F.round(F.avg("efficiency_pct"), 2).alias("avg_efficiency_pct"),
        F.sum("downtime_hours").alias("total_downtime_hours"),
    )
    agg.write.format("delta").mode("overwrite").saveAsTable(table_ref(SEMANTIC, "production_throughput_summary"))
    return agg.count()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

print("=" * 60)
print("Supply Chain Demo — Seeding all 19 Delta tables")
print("=" * 60)

counts = {{}}

print("\\n--- Bronze layer ---")
counts[table_ref(BRONZE, "raw_supplier_master")] = gen_supplier_master()
counts[table_ref(BRONZE, "raw_item_master")] = gen_item_master()
counts[table_ref(BRONZE, "raw_location_master")] = gen_location_master()
counts[table_ref(BRONZE, "raw_purchase_orders")] = gen_purchase_orders()
counts[table_ref(BRONZE, "raw_shipments")] = gen_shipments()
counts[table_ref(BRONZE, "raw_inventory_snapshots")] = gen_inventory_snapshots()
counts[table_ref(BRONZE, "raw_production_events")] = gen_production_events()

print("\\n--- Silver layer ---")
counts[table_ref(SILVER, "dim_supplier")] = build_dim_supplier()
counts[table_ref(SILVER, "dim_item")] = build_dim_item()
counts[table_ref(SILVER, "dim_location")] = build_dim_location()
counts[table_ref(SILVER, "fact_inventory_position")] = build_fact_inventory_position()
counts[table_ref(SILVER, "fact_order_cycle")] = build_fact_order_cycle()
counts[table_ref(SILVER, "fact_shipment_event")] = build_fact_shipment_event()
counts[table_ref(SILVER, "fact_production_output")] = build_fact_production_output()

print("\\n--- Semantic layer ---")
counts[table_ref(SEMANTIC, "supplier_otif_scorecard")] = build_supplier_otif_scorecard()
counts[table_ref(SEMANTIC, "inventory_risk_daily")] = build_inventory_risk_daily()
counts[table_ref(SEMANTIC, "demand_supply_gap")] = build_demand_supply_gap()
counts[table_ref(SEMANTIC, "logistics_cost_to_serve")] = build_logistics_cost_to_serve()
counts[table_ref(SEMANTIC, "production_throughput_summary")] = build_production_throughput_summary()

print("\\n" + "=" * 60)
print("ROW COUNT REPORT")
print("=" * 60)
for tbl, n in counts.items():
    print(f"  {{tbl:<60}} {{n:>8,}} rows")
print(f"\\n  Total tables created: {{len(counts)}}")
print("=" * 60)
'''


def upload_notebook(path, script):
    encoded = base64.b64encode(script.encode("utf-8")).decode("utf-8")
    payload = {
        "path": path,
        "format": "SOURCE",
        "language": "PYTHON",
        "content": encoded,
        "overwrite": True,
    }
    r = _post_raw("/api/2.0/workspace/import", payload)
    if r.status_code not in (200, 201):
        print(f"ERROR: Upload failed ({r.status_code}): {r.text}")
        sys.exit(1)
    return path


def submit_run(notebook_path):
    cluster_spec = {}
    if CLUSTER_ID:
        cluster_spec = {"existing_cluster_id": CLUSTER_ID}
    else:
        cluster_spec = {
            "new_cluster": {
                "spark_version": "15.4.x-scala2.12",
                "node_type_id": "Standard_DS3_v2",
                "num_workers": 0,
                "spark_conf": {"spark.databricks.cluster.profile": "singleNode"},
                "custom_tags": {"ResourceClass": "SingleNode"},
            }
        }

    payload = {
        "run_name": "supply_chain_demo_seed",
        "tasks": [
            {
                "task_key": "seed_all_tables",
                "notebook_task": {"notebook_path": notebook_path},
                **cluster_spec,
            }
        ],
    }
    result = _post("/api/2.1/jobs/runs/submit", payload)
    return result["run_id"]


def poll_run(run_id):
    elapsed = 0
    while elapsed < TIMEOUT_SECONDS:
        info = _get(f"/api/2.1/jobs/runs/get?run_id={run_id}")
        state = info.get("state", {})
        life = state.get("life_cycle_state", "")
        result = state.get("result_state", "")

        if life == "TERMINATED":
            return result, info
        if life in ("INTERNAL_ERROR", "SKIPPED"):
            return life, info

        print(".", end="", flush=True)
        time.sleep(POLL_INTERVAL)
        elapsed += POLL_INTERVAL

    return "TIMEOUT", {}


def fetch_output(run_id):
    try:
        out = _get(f"/api/2.1/jobs/runs/get-output?run_id={run_id}")
        return out.get("notebook_output", {}).get("result", "")
    except Exception:
        return ""


def main():
    preflight()

    print("Supply Chain Demo — Databricks Seed")
    print(f"  Host:    {HOST}")
    print(f"  Catalog: {CATALOG}.{{{BRONZE},{SILVER},{SEMANTIC}}}")

    notebook_base = resolve_notebook_path()
    seed_path = f"{notebook_base}/seed_all_tables"

    print(f"\nBuilding embedded seed script...")
    script = build_seed_script()

    print(f"Uploading seed notebook to {seed_path}...")
    upload_notebook(seed_path, script)
    print("  ✓ uploaded")

    print("\nSubmitting Databricks run...")
    run_id = submit_run(seed_path)
    run_url = f"{HOST}/#job/runs/{run_id}"
    print(f"  run_id: {run_id}")
    print(f"  url:    {run_url}")
    print(f"\nPolling (every {POLL_INTERVAL}s, timeout {TIMEOUT_SECONDS}s)...")

    result_state, run_info = poll_run(run_id)
    print()

    if result_state == "SUCCESS":
        print("\n✓ Run completed successfully.")
        output = fetch_output(run_id)
        if output:
            print("\n" + output)
        else:
            print("(no notebook output captured — check run logs in the Databricks UI)")
    else:
        state_msg = run_info.get("state", {}).get("state_message", "")
        print(f"\n✗ Run ended with state: {result_state}")
        if state_msg:
            print(f"  {state_msg}")
        print(f"\nRun details: {run_url}")
        sys.exit(1)


if __name__ == "__main__":
    main()
