import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "..");
const REGISTRY_PATH = path.join(ROOT, "config", "instruction-routing.json");
const GENERATED_MARKER = "<!-- generated by scripts/generate_instruction_artifacts.mjs -->";

function readRegistry() {
  return JSON.parse(fs.readFileSync(REGISTRY_PATH, "utf8"));
}

function skillWrapper(route) {
  const relativeSource = path
    .relative(path.join(ROOT, ".claude", "skills", route.claude_skill), path.join(ROOT, route.source))
    .split(path.sep)
    .join("/");
  return `---
name: ${route.claude_skill}
description: ${route.description}
---

${GENERATED_MARKER}

# ${route.id}

This is a Claude Code discovery wrapper. Before acting, read and follow the
canonical repository skill at \`${relativeSource}\` in full.

Keep this wrapper short. Update the canonical skill body, not this generated file.
`;
}

function instructionIndex(registry) {
  const rows = registry.routes
    .filter((route) => route.status === "active")
    .sort((left, right) => left.id.localeCompare(right.id))
    .map(
      (route) =>
        `| \`${route.id}\` | ${route.kind} | \`${route.source}\` | ${route.owners.join(", ")} | ${route.ado_risk} | ${route.delivery_profile} | ${route.claude_skill ? `\`/${route.claude_skill}\`` : "—"} |`,
    )
    .join("\n");

  return `---
id: instruction-index
kind: reference
status: informational
source_of_truth: false
topic: instruction-registry
owners:
  - docs
  - cross-repo
entrypoint: false
---

# Instruction Index

Generated from \`config/instruction-routing.json\`. Do not hand-edit this table.

The registry is the machine-readable routing source of truth. \`CLAUDE.md\`
contains only the durable startup contract. Root \`agents/*.md\` files are
OpenClaw role contracts; Claude-discoverable skills live under
\`.claude/skills/\` and delegate to canonical skill bodies.

| ID | Kind | Canonical source | Owners | ADO risk | Delivery | Claude command |
|---|---|---|---|---|---|---|
${rows}
`;
}

function collectSkillFiles(rootDir) {
  const roots = ["skills", ".skills", path.join("novendor-crm", "skills")];
  const files = [];

  function walk(directory) {
    if (!fs.existsSync(directory)) return;
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) walk(absolute);
      else if (entry.name === "SKILL.md") files.push(path.relative(rootDir, absolute));
    }
  }

  for (const relativeRoot of roots) walk(path.join(rootDir, relativeRoot));
  return files.sort((left, right) => left.localeCompare(right));
}

function skillsIndex(registry, rootDir) {
  const registeredBySource = new Map(
    registry.routes
      .filter((route) => route.kind === "skill")
      .map((route) => [route.source, route]),
  );
  const rows = collectSkillFiles(rootDir)
    .map((relativePath) => {
      const normalized = relativePath.split(path.sep).join("/");
      const route = registeredBySource.get(normalized);
      const name = path.basename(path.dirname(relativePath));
      return `| \`${normalized}\` | \`${name}\` | ${route ? "active route" : "available, not globally routed"} | ${route?.claude_skill ? `\`/${route.claude_skill}\`` : "—"} |`;
    })
    .join("\n");

  return `# Skills Index

Generated from skill files on disk plus \`config/instruction-routing.json\`.
Do not hand-edit this table.

\`skills/\` and \`.skills/\` contain repo-owned canonical skill bodies.
\`.claude/skills/\` contains generated Claude Code discovery wrappers.
\`novendor-crm/skills/\` belongs to the CRM package.

| Canonical path | Name | Routing status | Claude command |
|---|---|---|---|
${rows}
`;
}

export function generateInstructionArtifacts(rootDir = ROOT) {
  const registry = JSON.parse(
    fs.readFileSync(path.join(rootDir, "config", "instruction-routing.json"), "utf8"),
  );
  const skillsRoot = path.join(rootDir, ".claude", "skills");
  fs.mkdirSync(skillsRoot, { recursive: true });

  const expected = new Set();
  for (const route of registry.routes) {
    if (route.status !== "active" || !route.claude_skill) continue;
    expected.add(route.claude_skill);
    const skillDir = path.join(skillsRoot, route.claude_skill);
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(path.join(skillDir, "SKILL.md"), skillWrapper(route), "utf8");
  }

  for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
    if (!entry.isDirectory() || expected.has(entry.name)) continue;
    const generatedFile = path.join(skillsRoot, entry.name, "SKILL.md");
    if (
      fs.existsSync(generatedFile) &&
      fs.readFileSync(generatedFile, "utf8").includes(GENERATED_MARKER)
    ) {
      fs.rmSync(path.join(skillsRoot, entry.name), { recursive: true, force: true });
    }
  }

  fs.writeFileSync(
    path.join(rootDir, "docs", "instruction-index.md"),
    instructionIndex(registry),
    "utf8",
  );
  fs.writeFileSync(
    path.join(rootDir, "skills", "SKILLS_INDEX.md"),
    skillsIndex(registry, rootDir),
    "utf8",
  );
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  generateInstructionArtifacts();
  console.log("Generated Claude skill wrappers and instruction/skills indexes.");
}
