"""Ticket 4 — sync Lakebase serving tables from the BigQuery gold marts (serving_provenance='dataproc-gold').

The dashboards read the flat rel_* serving tables in Lakebase Postgres via FastAPI. This is the step
that makes BigQuery the *real* serving source: it reads gold_rel_* from BigQuery (produced by the
Dataproc PySpark medallion) and writes an idempotent SQL file that DELETEs the current batch and
re-INSERTs the gold rows with serving_provenance='dataproc-gold'. Apply with repo-b/db/schema/apply.js
using a minted Lakebase owner credential.

This replaces the retired Databricks read-back (rel_medallion.py::emit_serving_sql) — same serving
contract, BigQuery as the source instead of Databricks.

Mart -> serving table mapping and the serving column contract come from the generator's emit.py so the
Lakebase schema (migration 10038) is matched exactly.

Run:
    python telemetry-platform/dataproc/relativity_mes/sync_serving_from_bq.py \
        --project novendor-events-prod --dataset relativity_mes \
        --out telemetry-platform/dataproc/relativity_mes/rel_serving_dataproc_gold.sql
Then apply:
    DATABASE_URL=<lakebase-owner-url> node repo-b/db/schema/apply.js --files rel_serving_dataproc_gold.sql
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.relativity_mes_seed.generate import BUSINESS_ID, ENV_ID, INGEST_BATCH, build_dataset  # noqa: E402
from scripts.relativity_mes_seed.emit import SERVING_MAP, _columns, _infer_types, _lit  # noqa: E402

PROVENANCE = "dataproc-gold"


def _coerce(value, pg_type: str):
    if value is None:
        return None
    if pg_type == "boolean":
        return str(value).lower() in ("true", "t", "1")
    if pg_type == "numeric":
        try:
            return float(value)
        except (TypeError, ValueError):
            return value
    return value


def emit(project: str, dataset: str, out_path: Path) -> int:
    from google.cloud import bigquery

    # The generator gives us the authoritative column order + pg types for each serving table.
    ds = build_dataset()
    client = bigquery.Client(project=project)

    lines = [
        f"-- {out_path.name}  (GENERATED by sync_serving_from_bq.py — do not hand-edit)",
        "-- SYNTHETIC Relativity MES Sandbox: loads the Lakebase serving tables from the BigQuery gold",
        f"-- marts (gold_rel_*), produced by the Dataproc PySpark medallion. serving_provenance='{PROVENANCE}'.",
        "-- Idempotent: DELETE by ingest_batch_id then re-INSERT. Apply with repo-b/db/schema/apply.js.",
        "BEGIN;",
    ]
    e, b = f"'{ENV_ID}'", f"'{BUSINESS_ID}'"
    total = 0
    for mart, table in SERVING_MAP.items():
        cols = _columns(ds["gold"][mart])
        types = _infer_types(ds["gold"][mart])
        col_list = ", ".join(cols)
        rows = list(client.query(
            f"SELECT {col_list} FROM `{project}.{dataset}.gold_{table}`").result())
        lines.append(f"DELETE FROM {table} WHERE ingest_batch_id = '{INGEST_BATCH}';")
        insert_cols = ["env_id", "business_id"] + cols + ["serving_provenance"]
        values = []
        for r in rows:
            cells = [e, b]
            for c in cols:
                cells.append(_lit(_coerce(r[c], types[c]), types[c]))
            cells.append(f"'{PROVENANCE}'")
            values.append("  (" + ", ".join(cells) + ")")
        if values:
            lines.append(f"INSERT INTO {table} ({', '.join(insert_cols)}) VALUES")
            lines.append(",\n".join(values) + ";")
        total += len(values)
        print(f"[serving-sync] {table}: {len(values)} rows from gold_{table}")
    lines.append("COMMIT;")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[serving-sync] wrote {out_path} ({total} gold rows, provenance={PROVENANCE})")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default="novendor-events-prod")
    ap.add_argument("--dataset", default="relativity_mes")
    ap.add_argument("--out", default=str(Path(__file__).parent / "rel_serving_dataproc_gold.sql"))
    args = ap.parse_args()
    return emit(args.project, args.dataset, Path(args.out))


if __name__ == "__main__":
    sys.exit(main())
